### ISSUE TITLE
Not available for many barcodes as code93, code39, itf

### ISSUE THREAD

**Issue by nosakiis** [Spelt/ZXing.Delphi#102]
Hi,

While developing an android app, I tried Zxing.Delphi and the results are clear:
- It works for EAN8, EAN13, code128, UPC-A and UPC-E.
- This does not work for code 93, code 39, ITF (Particularly ITF14 which is important for logistics applications)

Particularly for GS1-128 (which is important for logistics applications), the barcodes are read as code 128 but digits are wrong if there are AI (Application Identifier) in the 128-barcode.

So with these limitations, it is not possible to use ZXing for a real logistics application but ZXing is a perfect solution for use limited to basic barcodes.

**Comment by Spelt** [comment]
Hi

You need to provide failing cases for barcodes that according to you do not work. 
Like for code 39, code 93 and ITF. 

If you need another barcode like GS1 code 128 you can implement it yourself like others did with other barcodes.  Im happy to test and integrate it. 

Sincerely Edward

**Comment by nosakiis** [comment]
Hi,

In the attached document, you will find 2 pages of different types of barcodes.

All these barcodes have been validated using a professional barcode reader. The ZXing Delphi library reads perfectly all the barcodes on the first page (ean13, upc-a, upc-e, code128) and only the ean14 barcode on the second page.

Other barcodes (ITF14 (=Interleaved2of5), code39, code93 and Interleaved2of5) cannot be recognized by ZXing.Delphi.

Best Regards

[BarcodesFormats3.pdf](https://github.com/Spelt/ZXing.Delphi/files/4794234/BarcodesFormats3.pdf)

**Comment by Spelt** [comment]
Hi Nosakiis,

I did a test with my Android Pixel 3a and the Advanced test app but all barcodes are scanned without any issue.

Which devices were you testing on?

**Comment by nosakiis** [comment]
Hi,

ZXing.Delphi extracts data by processing an image (bitmap) of a barcode.

Either the used device captures an image of sufficient quality for ZXing to read all the expected types of barcodes, or the image quality is insufficient and no type of barcodes can be recognized.

In our tests, the barcodes ean8, ean13, ean14, upc-a and upc-e are read by ZXing in one second and the others never!

I will test with different devices and different Android versions, but I doubt it will depend on the type of device.

Best Regards
