### ISSUE TITLE
[DCC Error] ZXing.StringUtils.pas(32): E2217 Published-Feld 'ASSUME_SHIFT_JIS' is neither class nor interface

### ISSUE THREAD

**Issue by AppSep** [Spelt/ZXing.Delphi#107]
Delphi 10.x
unit ZXing.StringUtils

[DCC Error] ZXing.StringUtils.pas(32): E2217 Published-Feld 'ASSUME_SHIFT_JIS' is neither class nor interface
[DCC Error] ZXing.StringUtils.pas(33): E2217 Published-Feld 'PLATFORM_DEFAULT_ENCODING' is neither class nor interface

Line 32 & 33

**old**
`
type

  TStringUtils = class abstract
  const
    UTF8 = 'UTF-8';
    EUC_JP = 'EUC-JP';
    ISO88591 = 'ISO-8859-1';
    class procedure ClassInit;
    class var ASSUME_SHIFT_JIS: boolean;
    class var PLATFORM_DEFAULT_ENCODING: string;
  public
    class var GB2312: string;
    class var SHIFT_JIS: string;
    class function guessEncoding(bytes: TArray<Byte>;
      hints: TDictionary<TDecodeHintType, TObject>): string; static;

  end;
`

**new**
`
type

  TStringUtils = class abstract
  const
    UTF8 = 'UTF-8';
    EUC_JP = 'EUC-JP';
    ISO88591 = 'ISO-8859-1';
    class procedure ClassInit;

  public
    class var GB2312: string;
    class var SHIFT_JIS: string;
    class var ASSUME_SHIFT_JIS: boolean;
    class var PLATFORM_DEFAULT_ENCODING: string;
    class function guessEncoding(bytes: TArray<Byte>;
      hints: TDictionary<TDecodeHintType, TObject>): string; static;

  end;
`

**Comment by Spelt** [comment]
Why do you want to make it public? 

I dont get compile errors. Which compiler and platform are you using?

Thanks!

Edward

**Comment by AppSep** [comment]
Hi,
Delphi 10.4.1
App for Win32/Win64/ios64/android64

**Comment by Spelt** [comment]
There is no need to make it public.
