### ISSUE TITLE
[DCC Error] ZXing.QrCode.Internal.FinderPattern.pas(71): E2266 Only one method from a group of overloaded methods can be published

### ISSUE THREAD

**Issue by AppSep** [Spelt/ZXing.Delphi#108]
Delphi 10.x
[DCC Error] ZXing.QrCode.Internal.FinderPattern.pas(71): E2266 Only one method from a group of overloaded methods can be published

Line 69 - 71

**old**

Line 69
   class function  CreateFinderPattern(const posX, posY, estimatedModuleSize: Single;
Line 80
 class function  TFinderPatternHelpers.CreateFinderPattern(const posX, posY, estimatedModuleSize: Single; const count: Integer):IFinderPattern;

**new**

Line 69
   class function  CreateFinderPattern_(const posX, posY, estimatedModuleSize: Single;
Line 80
 class function  TFinderPatternHelpers.CreateFinderPattern_(const posX, posY, estimatedModuleSize: Single; const count: Integer):IFinderPattern;

**Comment by Spelt** [comment]
Hi 

I don't have this errors.  The overload is working perfectly fine.

Which Delphi version and which platform are you using? 

Edward

**Comment by AppSep** [comment]
Hi,
Delphi 10.4.1
App for Win32/Win64/ios64/android64

**Comment by Spelt** [comment]
The overload is perfectly valid.
