### ISSUE TITLE
QR-code of one-digit numeric string is not recognized

### ISSUE THREAD

**Issue by ashumkin** [Spelt/ZXing.Delphi#11]
This issue is observed when I was fixing #9.
If a string is one-digit only. It is not recognized.
"Version number needs to be between 1 and 40" exception is occured.

I don't know (for now) how to correclty fix it.

**Comment by Spelt** [comment]
Ok Alexey thanks! 

I will also take a look at he pull request later this week.  This issue is a minor one.

**Comment by Spelt** [comment]
Hi Alexey

I uploaded v3.5 and it looks like this issue is fixed too. 

Can you verify this and report back?

**Comment by ashumkin** [comment]
Hi, Edward!
I've verified. It seems commit 168db6f769ef67841e5fadcbf995fe4e208caa2e fixes this issue. Thank you.
I'm gonna PR a test for this.

**Comment by ashumkin** [comment]
I close the issue. It is fixed with the 168db6f769ef67841e5fadcbf995fe4e208caa2e
