### ISSUE TITLE
How to read only 1D barcodes?

### ISSUE THREAD

**Issue by rojillo1** [Spelt/ZXing.Delphi#111]
Is there any way to instruct it to read only 1D codes?

Specifically, these would be the codes that you should only read:
UPC-A, UPC-E, EAN-8, EAN-13

Greetings.

**Comment by Spelt** [comment]
Yes you can do that with something like:

var listFormats := TList<TBarcodeFormat>.Create();

'add your formats to the listFormats here' like :
listFormats.Add(TBarcodeFormat.UPC_E);

var hints: TDictionary<TDecodeHintType, TObject>;
hints := TDictionary<TDecodeHintType, TObject>.Create();
Hints.Add(ZXing.DecodeHintType.POSSIBLE_FORMATS, listFormats);

ScanManager := TScanManager.Create(TBarcodeFormat.UPC_A, Hints);





Op ma 19 okt. 2020 om 20:15 schreef rojillo1 <notifications@github.com>:

**Comment by rojillo1** [comment]
Thanks spelt, it works perfectly.

Greetings.

**Comment by rojillo1** [comment]
I update the theme, with version 10.3.3 it works perfectly.

Today I have updated to version 10.4.1 and when I try to capture a barcode the image freezes and abruptly ends the program, I use this code:

```
var listFormats := TList<TBarcodeFormat>.Create();

'add your formats to the listFormats here' like :
listFormats.Add(TBarcodeFormat.EAN_8);
listFormats.Add(TBarcodeFormat.EAN_13);
listFormats.Add(TBarcodeFormat.UPC_A;
listFormats.Add(TBarcodeFormat.UPC_E);
listFormats.Add(TBarcodeFormat.UPC_EAN_EXTENSION);

var hints: TDictionary<TDecodeHintType, TObject>;
hints := TDictionary<TDecodeHintType, TObject>.Create();
Hints.Add(ZXing.DecodeHintType.POSSIBLE_FORMATS, listFormats);

ScanManager: = TScanManager.Create (TBarcodeFormat.auto, Hints);
```

Instead the program works correctly with this code:

`ScanManager: = TScanManager.Create (TBarcodeFormat.auto, nil);`


Greetings.
