### ISSUE TITLE
Recognition for slanted 1D barcode

### ISSUE THREAD

**Issue by Johan-Lee** [Spelt/ZXing.Delphi#112]
How to recognize a one-dimensional barcode image captured vertically or at various angles?

**Comment by Spelt** [comment]
It does 90 and 180 degrees with the data. 

I once investigated rotation on 45 but because of time constraints I could not continue. 

Easiest to accomplish is to feed the parser a bitmap which is rotated 45 degrees.

**Comment by Johan-Lee** [comment]
Thank you for the answer.
