### ISSUE TITLE
Transferring, content read from the barcode to the text field

### ISSUE THREAD

**Issue by vrrocha-git** [Spelt/ZXing.Delphi#114]
I did a mobile project for my tcc project using delphi CE and used Zxing to read the code and throw the content into the text field. When compiled in either 32 or 64 bits I can operate normally, if the android version is up to version 9, I can read the barcode for the text field normally, already in android 10, it opens the app for reading barcode, but the number read does not go to the text box! do you have any solution for this compatibility problem?

**Comment by Spelt** [comment]
Hi

What do you mean ‘throw to the textbox’  can you show some code?

If the number read is correct maybe this will help:

https://stackoverflow.com/questions/63682885/android-api-level-29-with-firemonkey-10-3-3-not-working-on-android-v-10-0-device
