### ISSUE TITLE
Cant read GS1 - EAN128 from Bartender 

### ISSUE THREAD

**Issue by 1Dragon** [Spelt/ZXing.Delphi#116]
hello Spelt,

thanks for sharing this work,
as i say, i cant read true GS1 - EAN128 barcodes made in Bartender,
do you have some work around for this?

thank you.

**Comment by Spelt** [comment]
Hi

Made in Bartender? What is that?

**Comment by 1Dragon** [comment]
hi Spelt

seriously ?
kkkk
simply the best barcode software in the world ;-)

https://www.seagullscientific.com/

except mine of course...
well i only automate Sap with fastreport,
in a imaginative way :-)

i made a simple mobile aplication for quality dep. read barcodes in a
product nspection,
we are upgrading our barcode to datamatrix and your lib works more then
well,
also read EAN128 fine, the problem is the change we made because GS
separator,
ASCII 29, so, we upgrade the EAN128 to GS1 EAN128 only because the
separators,
we have 6 AI that end with GS.

i see in your code an upgrade you made to GS1 but you are more advanced
then me,
if you have some idea how to solve this litle problem,
i would be very grateful,
however, tomorrow i wil fight with your beautiful code to try understand
and solve,
but you have many lines...

anyway, thanks for your response and this fantastic lib.





E Spelt <notifications@github.com> escreveu no dia terça, 9/02/2021 à(s)
21:37:

**Comment by Spelt** [comment]
Hi

I can't help you with that.   I don't find the time these days :-(   

The GS1 upgrade is probably made by a contributor.  Barcode types gets added and created by people who need it. 
When you have something (with some unit tests) I'm happy to test and intergrate fixes etc.

**Comment by 1Dragon** [comment]
Ok 👍

Thanks.

E Spelt <notifications@github.com> escreveu em sex., 12/02/2021 às 12:13 :
