### ISSUE TITLE
Is camera fixed In 10.4.2

### ISSUE THREAD

**Issue by RaySa74** [Spelt/ZXing.Delphi#119]
In the bug fixes in 10.4.2 they say the fixed the camera
. Can you please confirm. Thanks

https://quality.embarcadero.com/plugins/servlet/mobile#issue/RSP-10592

**Comment by Spelt** [comment]
That camera is not of my making. 

The best thing to do is install 10.4.2 yourself and test it yourself with the demo they provided.
