### ISSUE TITLE
Adding support for more barcodes formats

### ISSUE THREAD

**Issue by LecturePress** [Spelt/ZXing.Delphi#127]
The original ZXing for Java has added support for other formats like (Aztec, PDF 417, UPC/EAN Extension 2/5, ...).
Please, can you consider adding support for them in ZXing.Delphi ?

**Comment by Spelt** [comment]
Other barcodes?
Although it works extremely well, we still miss a few barcodes.For me there is no immediate need yet for me to implement more types but I like to add all of them! For that I need your help!

The base classes are already implemented so if you need to have another Barcode like Code39 (already done :-) ) you can see the C# source here: https://github.com/Redth/ZXing.Net.Mobile/blob/master/src/ZXing.Net/oned/Code39Reader.cs and convert it to Pascal. It's pretty easy (or just ask and I convert the raw classes for you).

If you want to help: Let us/me know which barcode you planning to implement. There is no point in converting barcodes multiple times :-)
