### ISSUE TITLE
Aztec

### ISSUE THREAD

**Issue by whitbrett** [Spelt/ZXing.Delphi#13]
Is anyone doing the Aztec barcodes?  If not, I might be able to help. I do not have a copy of reflector, so if you could run that for me, I would finish the conversion from there.  Thanks

**Comment by Spelt** [comment]
Not that I know off

**Comment by whitbrett** [comment]
Can you do the initial conversion to delhi.net for me?  I do not have Reflector setup.

**Comment by Spelt** [comment]
No problem.

**Comment by Spelt** [comment]
Here it is (attached). 14 files. 
Things like the ReedSolomonDecoder are already implemented (needed for QR-Code). 

With conversions:  please prepend class names with a T and try to use generic arrays (like TArray<TypeName>).

Hope it helps!

**Comment by Spelt** [comment]
![aztec](https://cloud.githubusercontent.com/assets/12660181/13648653/11d391ae-e63a-11e5-8fa9-de23efcb2ec9.jpg)

**Comment by Spelt** [comment]
Ok. I uploaded it as a .jpg file. Just download it and rename the extension to .zip.

I tested it and It should work.

**Comment by whitbrett** [comment]
Question for you.  Right now everything is lumped into the 2D directory.  Should there not be a 2D/Aztec and 2D/QRCode directory?

**Comment by whitbrett** [comment]
I also do not like the idea of having two files with the same name in the system.  I know that is not you, but the project.  Would you mind if I renamed the conflict ones in the Aztec directory.  I am referring to the files named Decoder for example.  Instead of Decoder.pas, make it AztecDecoder.pas, that way it will not conflict with other files in the future.  I know that it will be different than what is on the main project though.  What are your thoughts....

**Comment by Spelt** [comment]
No problem.

2016-03-10 0:35 GMT+01:00 whitbrett <notifications@github.com>:

**Comment by Spelt** [comment]
"Should there not be a 2D/Aztec and 2D/QRCode directory?"
Yes you can change this. Its a good suggestion.

**Comment by Spelt** [comment]
Hi WhitBrett,

I was adding some sources for the datamatrix barcode format and I noticed that I add AztecWriter.pas and Encoder.pas files to your zip.  These files are I think, not for reading but for writing barcodes which is out of the scope of the project.

**Comment by whitbrett** [comment]
Spelt, 

I saw that. After receiving the files, and working on it a little, I realized that this was way beyond what I had time to do right now. I even had another developer, that is a much better Delphi programmer than me, take a look at it. Personally, I am much more comfortable in C++ Builder than Delphi, but I wanted the ability to take this as a component in the future, and Delphi is the better option. The issue is that time is a very limited option for us right now. We can return and look at it some more when we have time. 

I would like to thank you for creating the files, it does show your dedication to the project. 

Thanks, 

Brett Whittacre 
Vice President 
whit@ec2software.com 
ec 2 Software Solutions 
3035 E. Patrick 
Ste. 1 
Las Vegas, Nevada, 89120 
P : 1.866.791.3673 ext 200 | F: 1.702.947.7357 
www.ec2software.com 
Follow the rules. Exceed the standard .

**Comment by Spelt** [comment]
Hi

Your welcome and I understand. 



> Op 20 mrt. 2016 om 16:33 heeft whitbrett <notifications@github.com> het volgende geschreven:
> 
> Spelt, 
> 
> I saw that. After receiving the files, and working on it a little, I realized that this was way beyond what I had time to do right now. I even had another developer, that is a much better Delphi programmer than me, take a look at it. Personally, I am much more comfortable in C++ Builder than Delphi, but I wanted the ability to take this as a component in the future, and Delphi is the better option. The issue is that time is a very limited option for us right now. We can return and look at it some more when we have time. 
> 
> I would like to thank you for creating the files, it does show your dedication to the project. 
> 
> Thanks, 
> 
> Brett Whittacre 
> Vice President 
> whit@ec2software.com 
> ec 2 Software Solutions 
> 3035 E. Patrick 
> Ste. 1 
> Las Vegas, Nevada, 89120 
> P : 1.866.791.3673 ext 200 | F: 1.702.947.7357 
> www.ec2software.com 
> Follow the rules. Exceed the standard . 
>
