### ISSUE TITLE
When a picture has more than one dimensional code or two-dimensional code

### ISSUE THREAD

**Issue by DValue** [Spelt/ZXing.Delphi#134]
What I mean is that when a picture has multiple one-dimensional codes or two-dimensional codes, can I return an array of scanning results? Due to technical reasons, I cannot achieve this

**Comment by Spelt** [comment]
Hi

There is no build in feature that support this. 

I guess there should be an internal list to skip the barcodes already scanned. 

I have no plans to build this. I though encourage the community to build this. I’m happy to assist.
