### ISSUE TITLE
Help,some qrcode  Unrecognized

### ISSUE THREAD

**Issue by caixc123** [Spelt/ZXing.Delphi#135]
![1](https://user-images.githubusercontent.com/20390238/192676517-6f56786a-bb41-42ff-9802-097894818c0f.jpg)
![无标题](https://user-images.githubusercontent.com/20390238/192676668-a5479e92-ef6e-4df7-b105-5f8b1ce99d72.jpg)

**Comment by geoffsmith82** [comment]
The bottom of it seems cut off

**Comment by Spelt** [comment]
Looks like a camera issue or a scaling issue with the original bitmap
scanned.
