### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by M3xR** [Spelt/ZXing.Delphi#136]
Hello i have a problem with reading QR codes.  
I am using FMXTestApp

it happens every time (sometime on first read, sometime on X read) and the error is in this 
```
Unit - ZXing.Common.BitArrayImplementation
Function - function TBitArrayImplementation.getNextUnset(from: Integer): Integer
Code - currentBits := currentBits and (not( (1 shl (from and $1F)) - 1))  (line 161)
```

I have 3.9.4 version
Android 32

**Comment by Spelt** [comment]
You mean any QR code? Or just one particular qr code?Which compiler do you use?Op 21 okt. 2022 om 14:17 heeft M3xR ***@***.***> het volgende geschreven:﻿
Hello i have a problem with reading QR codes.
I am using FMXTestApp
it happens every time (sometime on first read, sometime on X read) and the error is in this
Unit - ZXing.Common.BitArrayImplementation
Function - function TBitArrayImplementation.getNextUnset(from: Integer): Integer
Code - currentBits := currentBits and (not( (1 shl (from and $1F)) - 1))  (line 161)

I have 3.9.4 version
Android 32

**Comment by M3xR** [comment]
Any QR code or Barcode i am using online generator. I find out the error hapens only in debug mode. If i run application in mobile or run it without debugging the error will not show.
I am using Delphi 10.4

**Comment by Spelt** [comment]
This should be fixed now.
