### ISSUE TITLE
does not work anymore on ios16

### ISSUE THREAD

**Issue by DevintTechnology** [Spelt/ZXing.Delphi#138]
With iOS 16.3, no QRcode is scanned...
Thanks

**Comment by Spelt** [comment]
I tested the FMX demo application with Delphi Alexandria 11.3 with patch 1 installed.  I used an iPhone with IOS 16.1 with SDK 16.2 and it worked. The QR code is generated via: https://www.the-qrcode-generator.com/

I then updated to the latest: IOS 16.4.1 with SDK 16.4 and that works also.

I don't have access to IOS 16.3 so I can't verify it anymore. 

i'm closing this issue but please reopen when you don't agree or have other information.

**Comment by DevintTechnology** [comment]
Thanks for your tests !
I verify with the new version of Delphi (11.3)....

Bien Cordialement,

Régis GENDRAUD
