### ISSUE TITLE
Small bug - Count for Move must multiplied by element size in bytes

### ISSUE THREAD

**Issue by JedrzejczykRobert** [Spelt/ZXing.Delphi#143]
file: ZXing.ReadResult

line: 339, 340

current: 

```
  Move(oldPoints[0], newPoints[0], Length(oldPoints));
  Move(newPoints[0], newPoints[Length(oldPoints)], Length(newPoints));
```

should be:

```
  Move(oldPoints[0], allPoints[0], Length(oldPoints) * sizeof(allPoints[0]));
  Move(newPoints[0], allPoints[Length(oldPoints)], Length(newPoints) * sizeof(allPoints[0]));
```

or better:

```
  TArray.Copy<IResultPoint>(oldPoints, allPoints, 0, 0, Length(oldPoints));
  TArray.Copy<IResultPoint>(newPoints, allPoints, 0, Length(oldPoints), Length(newPoints));
```

or all function code can be minimized to:

`  FResultPoints := TArray.Concat<IResultPoint>([FResultPoints, newPoints]);`

**Comment by wwq0071** [comment]
then TArray.Concat function not supported in delphi ex10.2.3

**Comment by wwq0071** [comment]
the function TArray.Concat does not existed in the 10.2.3 version

**Comment by Spelt** [comment]
Yes its better to roll this one back. Op 24 aug. 2023 om 04:59 heeft wwq0071 ***@***.***> het volgende geschreven:﻿
the function TArray.Concat does not existed in the 10.2.3 version

**Comment by Spelt** [comment]
I have updated this one.

Thanks for your feedback!

Edward
