### ISSUE TITLE
Memory leak in TUPCEANExtension5Support.decodeRow

### ISSUE THREAD

**Issue by JedrzejczykRobert** [Spelt/ZXing.Delphi#148]
After apply #145 and like TUPCEANExtension2Support.decodeRow:

file: ZXing.OneD.UPCEANExtension5Support
line: 123

current:

```
  if (extensionData <> nil)
  then
     extensionResult.putAllMetadata(extensionData);
```

should be:

```
  if (extensionData <> nil) then
  begin
    extensionResult.putAllMetadata(extensionData);
    FreeAndNil(extensionData);
  end;
```

**Comment by Spelt** [comment]
Thanks Robert,I will check your fixes out in a couple of weeks. Op 1 jul. 2023 om 18:16 heeft Robert Jędrzejczyk ***@***.***> het volgende geschreven:﻿
After #145 and like TUPCEANExtension2Support.decodeRow:
file: ZXing.OneD.UPCEANExtension5Support
line: 123
current:
if (extensionData <> nil)
then
extensionResult.putAllMetadata(extensionData);
should be:
if (extensionData <> nil) then
begin
extensionResult.putAllMetadata(extensionData);
FreeAndNil(extensionData);
end;
