### ISSUE TITLE
TScanManager fall in multithread execution

### ISSUE THREAD

**Issue by Hadgehogs** [Spelt/ZXing.Delphi#157]
Hello.
Simple example:

`function test(Param: Pointer): THandle;
var
  ScanManager: TScanManager;
  ReadResult: TReadResult;
  aBitmap: TBitmap;
  res: TReadResult;
begin
  aBitmap := TBitmap.Create();
  aBitmap.LoadFromFile('C:\data.bmp');
  while True do
  begin
    ScanManager := TScanManager.Create(TBarcodeFormat.EAN_13, nil);
    res := ScanManager.Scan(aBitmap);
    if res <> nil then
      res.free;
    ScanManager.free;
  end;
end;

procedure TForm2.Button1Click(Sender: TObject);
var
  pid: Cardinal;
begin
  createthread(nil, 0, @test, 0, 0, pid);
  createthread(nil, 0, @test, 0, 0, pid);
end;
`
Get unhandled exception like this:
First chance exception at $00000000012D4870. Exception class $C0000094 with message 'c0000094 INTEGER_DIVIDE_BY_ZERO'. Process Project1.exe (11596)
at this code point:

![изображение](https://github.com/Spelt/ZXing.Delphi/assets/40996325/5fc36e57-8b32-413c-b6ad-7a556ce254de)

The reason for this is the use of class variables, which can change across threads without locking.

![изображение](https://github.com/Spelt/ZXing.Delphi/assets/40996325/ac6b47f4-b6a2-4656-a48a-8875237ea846)

![изображение](https://github.com/Spelt/ZXing.Delphi/assets/40996325/c721e69e-0844-4289-b842-061320daa92b)

**Comment by Hadgehogs** [comment]
ScanManager := TScanManager.Create(TBarcodeFormat.EAN_13, nil);
need change too:
ScanManager := TScanManager.Create(TBarcodeFormat.Auto, nil);

**Comment by Spelt** [comment]
This is not supported. Only one instance is supported.

Your improvement suggestion is probably not the only change to make, I do however accept pull requests :-)

It would be cool to run it parallel on multiple cores.
