### ISSUE TITLE
I am working on UPC

### ISSUE THREAD

**Issue by jimmckeeth** [Spelt/ZXing.Delphi#16]
Didn't see an easy way to message you, so thought I would add an issue. I am working on the UPCEANReader right now. The UPCAReader descends from it, which is what I am actually after.

Source: ZXing.Net.Mobile/Source/ZXing.Net/oned/UPCEANReader.cs

But my C# is a little rusty . . . .

**Comment by Spelt** [comment]
Hi Jim

No problem.


One person is working on Datamatrix and EAN at the same time.  Datamatrix
is his focus and EAN will be added later.  Don't know time estimations.
Perhaps you can do EAN?  There is already work done in branch v_3.0 See:
https://github.com/Spelt/ZXing.Delphi/tree/v_3.0/Lib/Classes/1D%20Barcodes
This will be the next branch to go live.







2016-05-11 5:49 GMT+02:00 Jim McKeeth <notifications@github.com>:

**Comment by jimmckeeth** [comment]
Thanks, I'll try to build off that and coordinate. . . .

**Comment by Spelt** [comment]
Ok, let me know if you need help.

btw saw the video.  The 1D scan strategie in the current zxing / .net implementation does scan opportunistic hence 1D barcodes does fail sometime when resolution is big. In v3 it is more aggressive and scans all lines with a step of n rows. Its is 5 now which is to tight and probably will change it to something more real world. 

Hope it helps!

Edward

**Comment by Spelt** [comment]
Did you have some progress?

**Comment by jimmckeeth** [comment]
I've not made any progress. I got pulled into some other work. I'll see if
I can circle back around and work on it.

-Jim McKeeth
jim@mckeeth.org
www.Delphi.org - The Podcast at Delphi.org
www.McKeeth.org - Personal home page

**Comment by Spelt** [comment]
yep, thats live.

> Op 30 aug. 2016, om 07:03 heeft Jim McKeeth notifications@github.com het volgende geschreven:
> 
> I've not made any progress. I got pulled into some other work. I'll see if
> I can circle back around and work on it.
> 
> -Jim McKeeth
> jim@mckeeth.org
> www.Delphi.org - The Podcast at Delphi.org
> www.McKeeth.org - Personal home page
>

**Comment by gkobler** [comment]
Are the EAN13 finished? I just read somthing about V3.1. But i just can download the V3.0

Best Regards
Gregor

**Comment by Spelt** [comment]
Unfortunately EAN is not completed yet. Jim’s a busy guy.

3.0 is not the production version although I have it working on my hardware without problems. It will be not the final release version, some minor changes will be made but they will not break things.

**Comment by gkobler** [comment]
may i can help you? I need the EAN13 in a project. The QR and Code128 are working well.

**Comment by Spelt** [comment]
Sure! If you want to you can continue in the latest v3. This is where it is left.

**Comment by gkobler** [comment]
Yes, but you have to tell me what i should do. I have seen that some EAN.... pas files are existing, but for me it's not clear what are not finished!

**Comment by Spelt** [comment]
Hi

The already created EAN files are best to be seen as a starting point. Its a conversion of the C# files with lots of work from Hofstede and Gossens (They also did the DataMatrix code which is 99% finished). 

What needs to be done is to get an EAN unit test up and running  and compare it to the c# code unit code test.  See what works and what doesn’t.   Then you need more barcodes to test (more unit test, with bigger and with real world images) 

It is not an easy task and it takes time but its worth it. You get eternal thanks in this git wiki and source code.

**Comment by gkobler** [comment]
Hi

I have made some changes and corrections. The unit test are running now without any access violations.

I have compared the original .cs with the .pas files, but when i try to decode the EAN13 barcode the method "Result := FMultiFormatReader.Decode(BinaryBitmap, true);" allwas returns NIL!

I have tryed to findout why, but it's not realy my business. :-(

Can i upload the changed code somewhere? May there are an other one how can check the code.

**Comment by Spelt** [comment]
Hi

Thanks, so your unit tests are running but not succeeding?

2016-10-12 10:39 GMT+02:00 gkobler notifications@github.com:

**Comment by gkobler** [comment]
Yes.. ;-)

**Comment by Spelt** [comment]
Well on the moment I don't have the time to debug it myself. Maybe someone
else has.

2016-10-12 17:42 GMT+02:00 gkobler notifications@github.com:

**Comment by gkobler** [comment]
of course. But can i upload my changes somewhere?

**Comment by Spelt** [comment]
Yes you can make a pull request.  You can read here about it:
https://help.github.com/articles/about-pull-requests/

2016-10-12 17:52 GMT+02:00 gkobler notifications@github.com:

**Comment by gkobler** [comment]
hi have made a pull request, but i do not know if I have done it right

**Comment by Spelt** [comment]
I dont see it  :-(

**Comment by gkobler** [comment]
https://github.com/gkobler/ZXing.Delphi

Can you access there?

**Comment by Spelt** [comment]
Hi,

Think that the pull request should be done via the original repo. GitHub is not always clear and easy to use. Nevertheless I could pull your branch into my local repo and I uploaded that new branch (gkobler-ean13) into the original remote repo.

If gkobler-ean13 works (and free of mem leaks) I shall merge it with the main v3 branch.

Thanks!
Edward

**Comment by Spelt** [comment]
EAN8 and EAN13 where released today. Since the base classes are UPCEAN (which is now implemented), UPC won't be far away.

**Comment by Spelt** [comment]
New release. UPC-A, UPC-E and Code 39 are just releases in v3.3

**Comment by gkobler** [comment]
Thanks a lot :-)
