### ISSUE TITLE
Data Matrix Decode error

### ISSUE THREAD

**Issue by makson5** [Spelt/ZXing.Delphi#162]
pls check this data matrix code

![mt](https://github.com/Spelt/ZXing.Delphi/assets/5002575/3a4109ef-3961-49d1-8bfb-6e01a4796cfe)

correct code is "~!@#$%^&*()_+}{POIUYTREWQASDFGHJKL:"?><MNBVCXZ`1234567890-=][poiuytrewqasdfghjkl;'/.,mnbvcxz|\"
but i got "~02981929*()_+}{POIUYTREWQASDFGHJKL:"?><MNBVCXZ`1234567890-=][poiuytrewqasdfghjkl;'/.,mnbvcxz|\"

seems its not support "!@#$%^&" to decode

btw: i use  demo\vclTestApp to test it

**Comment by Spelt** [comment]
Seems like a bug because if I feed the image to https://zxing.org/w/decode
it works.

**Comment by Spelt** [comment]
Fixed, release in a minute.
