### ISSUE TITLE
QRCode read error when contains '#10'

### ISSUE THREAD

**Issue by EguitarRed** [Spelt/ZXing.Delphi#163]
This QRcode:

![test_qr](https://github.com/Spelt/ZXing.Delphi/assets/33684165/563ad563-f506-4632-a6ec-9639097849aa)

Is readed incorrectly because the text contains #10.

I found an incorrect line code in ZXing.QrCode.Internal.DecodedBitStreamParser line 256.

I changed:

s:= res.toString.Replace('#13#10', '#10').Replace('#10', #13);

for:

s:= res.toString.Replace(#13+#10, #10).Replace(#10, #13);

And works correctly now.

**Comment by Spelt** [comment]
Thanks!

I will add the matrix code to the unit test and include the fix. Probably
this weekend.

I'm also testing and releasing for mobile and Delphi 12.

**Comment by EguitarRed** [comment]
I'm currently using Zxing on Delphi 12 and testing with android 12 and 13. Works correctly.

**Comment by Spelt** [comment]
Thanks,

I also did not experience a problem.

**Comment by Spelt** [comment]
Its commited and pushed. Thanks!
