### ISSUE TITLE
Scanner does not scan

### ISSUE THREAD

**Issue by FrankFinken** [Spelt/ZXing.Delphi#17]
Hi,

I'm new to android programming and I downloaded the ZXing.Delphi-master zip file. The test application compiled fine and starts on my S4, but the scanner does not read valid barcodes. 
The ReadResult in GetImage is always nil. I have set the focus mode as suggested in the oncamerclick 
(CameraComponent1.FocusMode := TFocusMode.ContinuousAutoFocus;)

For the rest the app is as downloaded. What am I missing/doing wrong here? Any help is greatly appreciated.

Delphi version is XE 10.1

Regards,
Frank

**Comment by Spelt** [comment]
Hi

What version of Delphi do you use?   Does the camera seems in focus? Is the
picture clear?





2016-06-01 0:18 GMT+02:00 FrankFinken <notifications@github.com>:

**Comment by FrankFinken** [comment]
Hi,

thanks for your reply. 

I'm using Delphi XE 10.1
The picture is clear and focussed. The ZXing barcode scanner app can read the barcodes.

**Comment by FrankFinken** [comment]
Tonight I will try using XE8.

**Comment by Spelt** [comment]
Did not test it on 10.1 But did test it on 10 (Seattle).

2016-06-01 14:29 GMT+02:00 FrankFinken <notifications@github.com>:

**Comment by FrankFinken** [comment]
If I build on my XE8 environment it also does not work. When I use intent code I can scan, but then I need the extenal scanner app.

var
  LIntent: JIntent;
begin
  // set OnActivityResult message handler
  FMessageSubscriptionID := TMessageManager.DefaultManager.SubscribeToMessage(TMessageResultNotification, HandleActivityMessage);

  // launch Barcode Scanner in SCAN mode
  LIntent := TJIntent.JavaClass.init(StringToJString('com.google.zxing.client.android.SCAN'));
  LIntent.setPackage(StringToJString('com.google.zxing.client.android'));
  LIntent.putExtra(StringToJString('SCAN_MODE'), StringToJString('ONE_D_MODE,QR_CODE_MODE,PRODUCT_MODE,DATA_MATRIX_MODE'));

  SharedActivity.startActivityForResult(LIntent, SCAN_REQUEST_CODE);

**Comment by Spelt** [comment]
Hi Frank

There should be no need for this ugly code ;-)   I do not have a S4 over here but on my androids it just works.

Could you zip the code and post it?  Then I can take a closer look.

**Comment by Spelt** [comment]
Question: How do the unit tests work?

**Comment by tcyhaveto** [comment]
@FrankFinken  Maybe you need change the Camera Quality Model as the following code: CameraComponent1.Quality:=TVideoCaptureQuality.MediumQuality;

**Comment by Rafdev86** [comment]
Hi
I'm using Delphi XE 10 Seattle

when I add  : CameraComponent1.FocusMode := TFocusMode.ContinuousAutoFocus; I get the following error : delphi java.lang.runtimeexception: setparameters failed.

Thanx for your help.

**Comment by Spelt** [comment]
Hi

Sounds not like a ZXing but a TCameraComponent issue.  Try the
TCameraComponent  in a stand alone application or try the demo application
first.


2016-06-08 12:08 GMT+02:00 Rafdev86 <notifications@github.com>:

**Comment by Rafdev86** [comment]
Hi Spelt,

I tested the TCameraComponent in a stand alone application with the TFocusMode I got the same error. 
Is there another solution to enable the TFocusMode?

**Comment by Spelt** [comment]
To be honest, I never encountered this error before.  Which Android
hardware do you use?

Few options to try:

1)

There is a bug in the TCameraComponent (XE7/XE8/10) which causes the
Android camera not to autofocus at all and therefore crippels the barcode
scanning. There is a work around which can be found here:
https://translate.google.nl/translate?sl=auto&tl=en&js=y&prev=
_t&hl=nl&ie=UTF-8&u=
http://tacotony.pixnet.net/blog/post/105520991-xe6%E7%82%BAtcameracomponent%E5%85%83%E4%BB%B6%E5%8A%A0%E4%B8%8A%E5%B0%8D%E7%84%A6%E5%8A%9F%E8%83%BD&edit-text=


2)
This project, https://github.com/gmurt/KernowSoftwareFMX is pretty neat
also and has maybe aTCameraViewer that you can use. I dont know if this
helps though but you can try the demo pretty quickly.



2016-06-08 15:25 GMT+02:00 Rafdev86 <notifications@github.com>:

**Comment by Rafdev86** [comment]
Hi Spelt,

I use Android 5.1.1 (API 22). Delphi XE 10 Seattle.
I tried the option 1, I had the same problem (I may be wrong tried).
Option 2, it doesn't contain TCameraViewer demo.

**Comment by Spelt** [comment]
He has a component though which is easy to setup.

Your TCameraComponent seems pretty weird: maybe you are suffering from:

There is a bug in the TCameraComponent (XE7/XE8/10) which causes the
Android camera not to autofocus at all and therefore crippels the barcode
scanning. There is a work around which can be found here:
https://translate.google.nl/translate?sl=auto&tl=en&js=y&prev=
_t&hl=nl&ie=UTF-8&u=
http://tacotony.pixnet.net/blog/post/105520991-xe6%E7%82%BAtcameracomponent%E5%85%83%E4%BB%B6%E5%8A%A0%E4%B8%8A%E5%B0%8D%E7%84%A6%E5%8A%9F%E8%83%BD&edit-text=




2016-06-09 12:03 GMT+02:00 Rafdev86 <notifications@github.com>:

**Comment by maurobotta** [comment]
I'm using Berlin on HTC One Max and Samsung S6 and aTestApp demo don't work

ReadResult in GetImage is always nil in ZXing.Delphi  V 3.1

i can see image on my app and "*******" chars,  but scanner don't read simple ean13 bar code

vclTestApp demo don't work for me, always scan result: "Unreadable!"

**Comment by Spelt** [comment]
Hi Mauro,

Unfortunately ean is not supported at this time. There was some work done but its not completed. 

Sincerely,
Edward
