### ISSUE TITLE
Please introduce ZXIng namespace and place all the units under such namespace

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#20]
Currently all the units of the project do not have a namespace in their name, so we have unit "Detector.pas" and not unit "ZXIng.Detector.pas".

This can be an issue because unit names must be unique within a delphi project and some of the units contained in this library have very generic names that can can easily clash with other unit names used by other libraries: "Decoder", "BitArray", "Helpers", "StringUtils"... are really too generic names and might very easily clash with unit names used by existing projects.
  I think that the most appropriate approach would be to put all unit names under the ZXing namespace (also for having more readable "uses" clauses).

**Comment by Spelt** [comment]
Hi 

The namespace issue is resolved in branch v_3.0 which is currently not yet the master due to a bug in the DataMatrix format. It will be live when the bug is fixed.

See:
https://github.com/Spelt/ZXing.Delphi/tree/v_3.0
