### ISSUE TITLE
Potential access violations in destructors (for Win32/Win64): they do not handle partial allocation in case of constructor failure

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#21]
The desctructor of an object gets called always, _even when the constructor itself has failed_.  This is done to allow the correct deallocation of all the possible objects that have been created during the partial execution of the constructor before it failed.
 The above statement is the reason for which the memory of any object being constructed is filled with zeros before calling the constructor itself, and it is also the reason for which the .Free method checks for nil self pointer before calling the actual .Destroy method under Win32.

Now: it is perfectly safe to call .Free on an object that has not been created in the constructor before it failed, because .Free does check for nil.. but ANY other operation you do in the destructor MUST check for the object being not nil using it. 

I noticed this problem in one of the destructors, but I suspect this potential problem is widespread across the sources

```
destructor TMultiFormatOneDReader.Destroy;
var
  Reader: TOneDReader;
begin
   // potential access violation here: you have NO guarantee that the Readers list has been correctly
   // initialized! the constructor could have failed before executing the .Create of the readers object.
   // in this case, here you would get an access violation (access to a nil pointer)
  for Reader in readers do
  begin
    Reader.Free;
  end;

  readers.clear;  // same problem here
  FreeAndNil(readers);
  inherited;
end;
```

The above code should have been written this way, otherwise any exception raised during the execution of the constructor could lead to an access violation inside the destructor:

```
destructor TMultiFormatOneDReader.Destroy;
var
  Reader: TOneDReader;
begin
  if readers <> nil then begin
        for Reader in readers do
              Reader.Free;

        readers.clear;  
   end;
   FreeAndNil(readers); // it is safe to pass a nil pointer to FreeAndNil: no need to check. 
                        // Same applies to object.free
   inherited;
end;
```

**Comment by Spelt** [comment]
Ok thanks for the feedback.

I will test it and merge if successful in https://github.com/Spelt/ZXing.Delphi/tree/v_3.0 

I keep this one open until more is known.

**Comment by Spelt** [comment]
fixed in branch 2, TMultiFormatOneDReader is deprecated in branch 3
