### ISSUE TITLE
Memory leak in THybridBinarizer.BinarizeEntireImage under Win32/Win64

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#22]
Here you are setting a pointer to nil instead of Freeing the object you just created... This is fine only of ARC compilers:

```
      newMatrix := TBitMatrix.Create(width, height);
      calculateThresholdForBlock(luminances, subWidth, subHeight, width, height,
        blackPoints, newMatrix);

      self.matrix := newMatrix;
    end;

  finally
    newMatrix := nil;  <<< THIS SHOULD BE newmatrix.free!
    SetLength(blackPoints,0);
    blackPoints := nil;
    luminances := nil;
  end;
end;
```

**Comment by Spelt** [comment]
Ok, I did not receive a memory leak but I see what you mean. Did you use a special memory tool? and if so which one?

I will check this out and if successful I merge it with https://github.com/Spelt/ZXing.Delphi/tree/v_3.0 which will become the new master branch when a exotic bug gets fixed.

I'll keep this one open until more is known.

**Comment by csm101** [comment]
Not a bug: i overlooked the "self.matrix := newMatrix" line... 
anyway the compiler warns that the assigment newmatrix := nil in the finall session is useless

**Comment by csm101** [comment]
I was about to close the issue myself right now :)
