### ISSUE TITLE
Access violation in TScanManager.Scan under Win32/Win64

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#23]
simple variables created on the stack (i.e: local variables declared in procedures) are NOT initialized with a default value under Win32/Win64. They contain random data.
  Simple variables are: pointers, integers, floats, object references, etc... 
  the only local variables (under non -ARC compilers) that get automatically initialized are those that have an implicit reference counting mechanism (interfaces, strings, dynamic arrays, variants) that would be broken if the variable doesn't always get initialized.:
the Win32/Win64 compiler initializes to zeros ONLY MEMBER VARIABLES of an object, before calling its constructor, and this is done only to allow the destructor (that gets called always, even if the constructor failed) to have a way to recognize which member variables have been allocated and which not (otherwise they would be all pointing to random memory addresses)

 In second place: it is perfectly safe to call .Free on a NIL pointer, since the implementation of .Free is this:

```
procedure TObject.Free;
begin
// under ARC, this method isn't actually called since the compiler translates
// the call to be a mere nil assignment to the instance variable, which then calls _InstClear
{$IFNDEF AUTOREFCOUNT}
  if Self <> nil then  // IT ALREADY CHECKS FOR NIL! 
    Destroy;             // the real deallocation happens in the destructor destroy that is called only if self<>nil
{$ENDIF}
end;
```

So, get back to the source code of TScanManager:

```
function TScanManager.Scan(pBitmapForScan: TBitmap): TReadResult;
var
  // ALL THESE VARIABLES ARE POINTERS POINTING TO RANDOM MEMORY ADDRESSES
  // IF YOU DON'T INITIALIZE THEM. the
  RGBLuminanceSource: TRGBLuminanceSource;
  HybridBinarizer: THybridBinarizer;
  BinaryBitmap: TBinaryBitmap;
begin
  try
    RGBLuminanceSource := TRGBLuminanceSource.RGBLuminanceSource(pBitmapForScan,
      pBitmapForScan.Width, pBitmapForScan.Height);

    HybridBinarizer := THybridBinarizer.Create(RGBLuminanceSource);

    BinaryBitmap := TBinaryBitmap.BinaryBitmap(HybridBinarizer);

    Result := FMultiFormatReader.Decode(BinaryBitmap, true);
  finally

    // since BinaryBitmap has been declared in the stack you have absolutely NO GUARANTEE  
    // that it is Nil if you do not assign explicitly nil to it
    // so here you are having random access violations because the value of BinaryBitmap is random!
    if (BinaryBitmap <> nil) then   // this test is totally redundant! .Free does it already internally.
    begin
      BinaryBitmap.Free;
    end;

    if (HybridBinarizer <> nil) then
    begin
      HybridBinarizer.Free;
    end;

    if (RGBLuminanceSource <> nil) then
    begin
      RGBLuminanceSource.Free;
    end;
  end;
end;

```

So, the above code should have been written this way:

```
function TScanManager.Scan(pBitmapForScan: TBitmap): TReadResult;
var
  RGBLuminanceSource: TRGBLuminanceSource;
  HybridBinarizer: THybridBinarizer;
  BinaryBitmap: TBinaryBitmap;
begin
  RGBLuminanceSource:=nil;
  HybridBinarizer:=nil;
  BinaryBitmap:=nil;
  try
    RGBLuminanceSource := TRGBLuminanceSource.RGBLuminanceSource(pBitmapForScan,
      pBitmapForScan.Width, pBitmapForScan.Height);

    HybridBinarizer := THybridBinarizer.Create(RGBLuminanceSource);

    BinaryBitmap := TBinaryBitmap.BinaryBitmap(HybridBinarizer);

    Result := FMultiFormatReader.Decode(BinaryBitmap, true);
  finally
      // now this is safe because the variables are either pointing to a valid object or 
      //  are still pointing to nil
      BinaryBitmap.Free;     
      HybridBinarizer.Free;
      RGBLuminanceSource.Free;
  end;
end;
```

or this way, if you want to be pedantic about how memory allocations should be handled with try/finally and you want to write code that calls each .free only if the corresponding allocation actually did succeed:

```
function TScanManager.Scan(pBitmapForScan: TBitmap): TReadResult;
var
  RGBLuminanceSource: TRGBLuminanceSource;
  HybridBinarizer: THybridBinarizer;
  BinaryBitmap: TBinaryBitmap;
begin
  // here I create a try/finally block for each object I create. this is the ONLY correct way
  RGBLuminanceSource := TRGBLuminanceSource.RGBLuminanceSource(pBitmapForScan,
      pBitmapForScan.Width, pBitmapForScan.Height);
  try
    HybridBinarizer := THybridBinarizer.Create(RGBLuminanceSource);
    try
        BinaryBitmap := TBinaryBitmap.BinaryBitmap(HybridBinarizer);
        try
            Result := FMultiFormatReader.Decode(BinaryBitmap, true);
        finally
          BinaryBitmap.Free;
        end
    finally
      HybridBinarizer.Free;
    end;
  finally
      RGBLuminanceSource.Free;
  end;
end;
```

So, to summarize: there are TWO possible patterns you can use to handle correct handling of deallocation of local variables. I know that both are useless if you are writing android/ios code because of the ARC compiler, but If you want to write code that correctly runs also on Win32/Win64, you have to use them:

first pattern: initialize all local variables to nil, write only one try/finally block and create the objects inside the try/finally 

```
    a := nil;
    b := nil;
    try
        a := TMyObject.Create;
        b := TMyOtherObject.Create;
    finally
        b.free;
        a.free;
    end;
```

second pattern create a try/finally block for EACH variable and allocate each variable immediately BEFORE entering the try/finally block (you want the finally to be run only if the creation did succeed):

```
    a := TMyObject.Create;
    try
        b := TMyOtherObject.Create;
        try
           ....
        finally
           b.free;
        end;
    finally
        a.free;
    end;
```

please note that this following example, without any initialization to nil before entering the try/finally block is WRONG:

```
    try
       a := TMyObject.Create;
       ...
    finally
        a.free;
    end;
```

I know that this post sounds more like a lesson in delphi programming than a proper bug report, but i think that this bug is caused only by the fact you are writing and testing only for the ARC compiler (android/ios) and maybe you don't have any experience on the other platforms, so I preferred to give you these insights.

 Actually what I did to notice these bugs was just to to look at the compiler warnings...

**Comment by Spelt** [comment]
Hi, thanks again for your feedback! Only like this we can make it better.

The code is a port from .Net where things get initialized different. Anyway the code is also targeted for Win32/Win64 so yes I will take a look, change it and run the tests. If successful I will merge it with the new branch https://github.com/Spelt/ZXing.Delphi/tree/v_3.0 coming soon. 

a lesson learned I have to say :-)
