### ISSUE TITLE
Scanning more than one barcode in an image

### ISSUE THREAD

**Issue by DelProgger** [Spelt/ZXing.Delphi#28]
Hi,
I just tried the lib and found it pretty useful. 

For some reasons I use it in an VCL (XE7) test project. It works fine so far (made some minor changes to the source just for testing). 

Now I would like to scan several barcodes in an image. Is there an easy way to achieve this? Up to now only one barcode is found.

Any hint welcome ;-)

**Comment by Spelt** [comment]
Scanning multiple barcodes is not supported.  

In the coming branch 3.0 the scan strategy is more aggresive for 1D barcodes.  

i would imagine that a catch all barcodes mode would involve blanking out the current barcode scanned somehow and then refeed the new bitmap.

**Comment by DelProgger** [comment]
Hi,
thanx for the reply!

I had a similar idea to solve this. As the TReadResult delivers the resultPoints there seems to be a way to kind of 'partition' the image and scan each partition then.
