### ISSUE TITLE
Read barcode not work

### ISSUE THREAD

**Issue by medreis** [Spelt/ZXing.Delphi#29]
Hello,

I am using the example, but does not read any code bars, put on Android, but Windows does not scan.

I am using delphi Seattle

You know what might be happening?

Marcio

**Comment by Spelt** [comment]
Do you get the bitmaps from your TCamera Component ?

2016-08-10 14:59 GMT+02:00 medreis <notifications@github.com>:

**Comment by Spelt** [comment]
Ping.. is it working now?
