### ISSUE TITLE
Trying UPCEANReader

### ISSUE THREAD

**Issue by fredycc** [Spelt/ZXing.Delphi#3]
First of all, thank you the great effort for QR-Code, Code 128, Code93 codes. Works great!

Device:
 -SM-G800H
 -Android 4.4.2
 -Autofocus (only modifying FMX.Media.pas the file as shown in note to android and initializing the               component with this code:
CameraComponent.SetFocusMode (TFocusMode.ContinuousAutoFocus))
-Camera Resolution: 352 x 288 x 15 fps is enough.

Delphi
Seattle Upd 1

I installed Reflector version 9.

I see the option of Delphi but marked as deprecated. But works in some way.

I have questions about a condition which can not understand the goal also marks errors, is the following:

    if (resultPointCallback <> nil) then
            resultPointCallback.Invoke(TResultPoint.Create(((startGuardRange[0] + startGuardRange[1]) div 2), rowNumber));

Errors: 
     UPCEANReader.pas(295): E2035 Not enough actual parameters
     Undeclared identifier 'Invoke'

I would appreciate your support. It is noteworthy that C # only know the basics.

Thank you

**Comment by Spelt** [comment]
Hi Freddy,

Thanks for the compliment.  

Regarding the problem: 
The resultpoint callback is not really needed as the resultpoints are returned in the result for optional further processing. Look for an example in the Code128Reader.pas (line 657-688).

**Comment by fredycc** [comment]
Thanks Spelt, I'll check.

**Comment by Spelt** [comment]
Hi Fredy

How did it go?  Did you succeed? or do you need some help?




2016-01-04 16:55 GMT+01:00 fredycc <notifications@github.com>:

**Comment by fredycc** [comment]
I appreciate your comment Spelt.

I noticed that you commented lines and I've already done.

But there are still several kinds or more units needed to see if it really works as the code generated by reflector 9 is necessary to rearrange the code.

I hope to make progress.

Thank you

**Comment by Spelt** [comment]
got it working? glad to help.

**Comment by fredycc** [comment]
Thanks Spelt. So far I have not had a chance to work, I hope to continue as soon as possible and try to compile.
