### ISSUE TITLE
main.fmx (in aTestApp) is a 3 megabyte file. is it necessary?

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#33]
Just a minor thing: I've noticed that the main form of the test app contains a non-empty bitmap.
Actually It contains seven different bitmaps and this makes main.fmx a huge source file.

Is this wanted for debugging purposes or they have been created by just activating the camera component at design time and they were afterwards left in the sources?

![image](https://cloud.githubusercontent.com/assets/5736859/18047490/81a3b894-6ddd-11e6-8afe-5aa43429b08f.png)

**Comment by Spelt** [comment]
Seems like a left over for testing purposes. I’ve cleaned it up and pushed it.
