### ISSUE TITLE
This QRCode (version 25) is not recognized by V3.0

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#35]
I've noticed that this qr-code is not recognized by current version. I downloaded it from the wikipedia page about qr-codes

![qr_droid_2663](https://cloud.githubusercontent.com/assets/5736859/18048316/aed229be-6de1-11e6-8391-ef1c61484bd3.png)

**Comment by Spelt** [comment]
It does not get recognized either in the ZXing online checker. https://zxing.org/w/decode.jspx https://zxing.org/w/decode.jspx 

It looks like other scanners like zbar doesn’t recognize it either.

**Comment by csm101** [comment]
the scanner app in my mobile phone does recognize it...  well,  I am just
reporting it.  I do not need to scan them in my apps.. it is not blocking
for me.

**Comment by Spelt** [comment]
which scan app is that?

> Op 29 aug. 2016, om 14:06 heeft Carlo Sirna notifications@github.com het volgende geschreven:
> 
> the scanner app in my mobile phone does recognize it... well, I am just
> reporting it. I do not need to scan them in my apps.. it is not blocking
> for me.
>

**Comment by csm101** [comment]
its the one that comes with Xiaomi mobile phones,  which use a modified
version of Android called MIUI . I don't know if it can be installed as a
separate app on standard android devices, since I think it is part of the
whole MIUI distribution.
MIUI is an open project and can be installed also on many non-xiaomi
phones,  but i don't think you are going to try it just for a barcode.

anyway the text contained seems to be the same text used in the qr code
version 40 example (in the same wikipedia page).
I am witing from my phone,  and this is the scanned text:

```
Version 40 QR Code can contain up to 1852 chars.
A QR code (abbreviated from Quick Response code) is a type of matrix
barcode (or two-dimensional code) that is designed to be read by
smartphones. The code consists of black modules arranged in a square
pattern on a white background. The information encoded may be text, a URL,
or other data.
Created by Toyota subsidiary Denso Wave in 1994, the QR code is one of the
most popular types of two-dimensional barcodes. The QR code was designed to
allow its contents to be decoded at high speed.
The technology has seen frequent use in Japan and South Korea; the United
Kingdom is the seventh-largest national consumer of QR codes.
Although initially used for tracking parts in vehicle manufacturing, QR
codes now are used in a much broader context, including both commercial
tracking applications and convenience-oriented applications aimed at mobile
phone users (termed mobile tagging). QR codes may be used to display text
to the user, to add a vCard contact to the user's device, to open a Uniform
Resource Identifier (URI), or to compose an e-mail or text message. Users
can generate and print their own QR codes for others to scan and use by
visiting one of several paid and free QR code generating sites or apps.
```

**Comment by Spelt** [comment]
Ok found one here called DataMatrix scanner which seems to scan it. 

> Op 29 aug. 2016, om 14:15 heeft Edward Spelt edwardspelt@gmail.com het volgende geschreven:
> 
> which scan app is that?
> 
> > Op 29 aug. 2016, om 14:06 heeft Carlo Sirna <notifications@github.com <mailto:notifications@github.com>> het volgende geschreven:
> > 
> > the scanner app in my mobile phone does recognize it... well, I am just
> > reporting it. I do not need to scan them in my apps.. it is not blocking
> > for me.
> >

**Comment by Spelt** [comment]
I did make a case on Stackoverflow as at zxing (github) they only accept patches . http://stackoverflow.com/questions/39223894/qr-code-is-not-recognized-by-zxing

**Comment by Spelt** [comment]
In Rio 10.3.2. this is still occuring. 

For IOS 64, I recommend a native IOS Camera component which has build in QR code detection.  This is build in in the last major versions of IOS. Build in QR detection is pretty good, other codes are not so good.
In a commercial app I build I use both.

Issue will continue when there is a better debugger available.

**Comment by Spelt** [comment]
ZXing only supports up to v20 QR code at mobile client, you can find from the source codes, I attach the codes as follows:

protected static final int MAX_MODULES = 97; // support up to version 20 for mobile clients

https://stackoverflow.com/questions/39223894/qr-code-is-not-recognized-by-zxing
