### ISSUE TITLE
Missing ZXingCommon.pas on ZIP file

### ISSUE THREAD

**Issue by jesus-beltran** [Spelt/ZXing.Delphi#4]
The file is missing, so the library and samples can't be compiled.

**Comment by Spelt** [comment]
Can you check if you have the latest version? If I download the zip I can run the projects.  If I get the source via Git it also just works.

**Comment by EliseoGN** [comment]
Hi, I have the same problem, 
I have already downloaded the zip file, even via Git version control and ZXingCommon.pas is missing. 

I hope you can help us.

Regards from Mexico City.

**Comment by Spelt** [comment]
Can you attach the zip to issue? 

Ps the zxingCommon is not needed because it is empty, but I will investigate.

**Comment by EliseoGN** [comment]
Hi, here is what you requested.

Regards

[ZXing.Delphi-master.zip](https://github.com/Spelt/ZXing.Delphi/files/107665/ZXing.Delphi-master.zip)

**Comment by Spelt** [comment]
Ok thanks.

I think see the confusion. Did you try to build the .dpk ? It was an old
file which was a attempt to include the library as a dynamic package but
that is not supported in FMX mobile.

For now you need to just include the files. Maybe there will be a static
component in the future for ease of use and faster build times.

You need to open the solution file and try to run dxUnitXTest to verify if
everything is working properly. After this check out the TestApp project
for an example.


Hope it helps!  Please let us know.





2016-01-28 4:52 GMT+01:00 EliseoGN <notifications@github.com>:

**Comment by EliseoGN** [comment]
Thanks for your replay, I will do what you suggest and I will let you know about it.

Regards.
