### ISSUE TITLE
App auto close after open on iphone 6 plus

### ISSUE THREAD

**Issue by fuandi** [Spelt/ZXing.Delphi#41]
Compiled the source code using delphi 10 seattle and run it on iphone 6 plus.
After I open the app, it will auto close immediately. Appreciate if you can help. Thanks

**Comment by Spelt** [comment]
Currently im on a short holiday but some quick questions
- Are you using the demo app?
- Which branch are you using?

**Comment by fuandi** [comment]
yes, i'm using aTestapp
what do you mean by branch ?

**Comment by Spelt** [comment]
Do you use the master branch or branch v3?
