### ISSUE TITLE
Code 39 not working very well

### ISSUE THREAD

**Issue by jdredd87** [Spelt/ZXing.Delphi#42]
Berlin 10.1 Update 1

Android

HTC One (E8) 0PAJ5

Code 39 just doesn't seem to work very well at detecting.
Code 39 Extended doesn't seem to work well either.

I can scan it seems any random Code 128 and it seems to be very responsive and correct.

Just seems 39 codes are not processing very well at all.

Played with quality levels but doesn't seem to do any help.

**Comment by jdredd87** [comment]
Never mind. I am dumb. It looks like Code39 is not supported. 

Oddly it has picked up a few codes just not many at all.

**Comment by nano103** [comment]
I create pull request with code 39 support. You can try to use my fork to test it

**Comment by Spelt** [comment]
I'll put it on the list.

**Comment by Spelt** [comment]
Hi
Code 39 is now officially in the 3.0 Branch.  Please update because the version you offered contains some bugs.

**Comment by nano103** [comment]
Thanx!

**Comment by nano103** [comment]
Hi
I suppose some fixes are necessary to conform Code39Reader.cs:

 Lib/Classes/1D Barcodes/ZXing.OneD.Code39Reader.pas | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/Lib/Classes/1D Barcodes/ZXing.OneD.Code39Reader.pas b/Lib/Classes/1D Barcodes/ZXing.OneD.Code39Reader.pas
index 40079cc..ebcf61d 100644
--- a/Lib/Classes/1D Barcodes/ZXing.OneD.Code39Reader.pas	
+++ b/Lib/Classes/1D Barcodes/ZXing.OneD.Code39Reader.pas	
@@ -130,7 +130,8 @@ begin
               if ((next >= 'A') and (next <= 'Z')) then
               begin
                 decodedChar := Char(ord(next) + 32);
-              end;
+              end
+              else
               begin
                 exit('');
               end
@@ -140,7 +141,8 @@ begin
               if ((next >= 'A') and (next <= 'Z')) then
               begin
                 decodedChar := Char(ord(next) - 64);
-              end;
+              end
+              else
               begin
                 exit('');
               end

**Comment by Spelt** [comment]
Hi

is it possible to make a pull request?  There is a link on github with help
on how to do that. I can make a fix easily that way. Also can you provide a
failing test? which should succeed after the patch? That way we can make
sure this will not happen again.





2017-01-07 0:03 GMT+01:00 nano103 <notifications@github.com>:

**Comment by nano103** [comment]
ok, i'll make pull request
the patch is just 2 "else" to add

it was not any particular fails - at least 2 warnings in compilation will be eliminated and decoding logic will conform to .cs source, delphi source based on

Отправлено с iPhone
