### ISSUE TITLE
can not decoder 2D datamatrix ?

### ISSUE THREAD

**Issue by dbyoung720** [Spelt/ZXing.Delphi#43]
can not decoder 2D datamatrix ?

**Comment by Spelt** [comment]
Hi

In branch 3 it is implemented but there is still a bug in datamatrix. Hence it is not released yet.

**Comment by Spelt** [comment]
It is released as beta. I think there is still an issue. It works only when the barcode is in the centre.  This is also happening in the original source. I did make an bug report.
