### ISSUE TITLE
can not decoder code_128A?

### ISSUE THREAD

**Issue by dbyoung720** [Spelt/ZXing.Delphi#45]
can not decoder code_128A?

**Comment by Spelt** [comment]
Hi it should scan all Code 128 formats.

Do you experience issues with Code 128 A ?

2016-11-24 6:30 GMT+01:00 dbyoung720 <notifications@github.com>:

**Comment by Spelt** [comment]
Ping ! Please answer or I will close this issue.

**Comment by dbyoung720** [comment]
YES, can decoder code128.
