### ISSUE TITLE
F2613 Unit 'TestInsight.DUnitX' not found.

### ISSUE THREAD

**Issue by vurmak** [Spelt/ZXing.Delphi#51]
Hi,
I installed your project but I have an error. aTestApp.exe, vclTestApp.exe and Leaktest.exe are working but dUnitXTest.exe is not working. What should I do?

Thank you from now.

**Comment by Spelt** [comment]
Hi,

Did you install testinsight ?  You can find it here:
https://bitbucket.org/sglienke/testinsight/wiki/Home

It is an easy test runner.

Maybe you have to install dunitx too, but im not sure about that. It
probably is default in delphi.






2017-01-24 10:08 GMT+01:00 vurmak <notifications@github.com>:

**Comment by vurmak** [comment]
You are right. I installed, programme run. Thank you.

**Comment by Spelt** [comment]
Great. Have fun with it.
