### ISSUE TITLE
Codabar support

### ISSUE THREAD

**Issue by fiiQ** [Spelt/ZXing.Delphi#54]
Hi Spelt

could you add one more barcode type support plz! its 'Codabar'
there was app i made use this codabar barcode and to read it i use barcode reader device.
and next, i want to make another barcode reader from smartphone

thanks alot

fiiq

**Comment by Spelt** [comment]
Hi

You have to translate it yourself, add tests and do a pull request so I can
review it.  This is how it works.

If you serious about it, I can supply you the raw automatic .net to pascal
translation.


2017-04-26 14:39 GMT+02:00 fiiQ <notifications@github.com>:

**Comment by fiiQ** [comment]
yup.. I'd like to try it :)

and the page you provide for C# source is not there anymore or moved

**Comment by Spelt** [comment]
Ok I will post the code in a couple of days.

2017-05-02 4:10 GMT+02:00 fiiQ <notifications@github.com>:

**Comment by Spelt** [comment]
[codabar.pascal.net.txt](https://github.com/Spelt/ZXing.Delphi/files/980001/codabar.pascal.net.txt)

Hi, here it is.

Take a good look at its base class so you can see some naming differences with this file.  For example: DecodeHintType must be TDecodeHintType.

Anyway, success !

**Comment by Spelt** [comment]
And don't forget to add plenty of unit tests !

**Comment by eugene4bond** [comment]
Everyone who needs CodaBar in ZXing.Delphi.
I builded new class library and attached them to Reader. Work fine in my projects. 

[ZXing.OneD.CodaBarReader.zip](https://github.com/Spelt/ZXing.Delphi/files/3068905/ZXing.OneD.CodaBarReader.zip)
