### ISSUE TITLE
Fix To Assignment of Metadata

### ISSUE THREAD

**Issue by SteveCorbett** [Spelt/ZXing.Delphi#59]
In ZXing.ReadResults an internal variable (FResultMetadata) is being assigned to an external variable in procedure putAllMetaData if it is not already assigned.

This causes problems when compiled for Windows.

I've included a patch for this: [patch3.zip](https://github.com/Spelt/ZXing.Delphi/files/1210154/patch3.zip)

**Comment by Spelt** [comment]
Sorry for the delay, was on a long holiday.

Its patched, many thanks!
