### ISSUE TITLE
IOS 9 not working

### ISSUE THREAD

**Issue by mrcarromesa** [Spelt/ZXing.Delphi#6]
Once the app is installed in IOS 9 he is dead.
Does not run.
Made with Delphi 10.
Because?

**Comment by Spelt** [comment]
Its working on IOS 9 here without problems. Did you try the demo app?

Verstuurd vanaf mijn iPad

**Comment by mrcarromesa** [comment]
The IOS 9 32-bit run normally.
But the IOS 9 64-bit not working,
My device is an iPhone 5s

**Comment by mrcarromesa** [comment]
Problem solved.
in the file StringUtils.pas
change: 
ASSUME_SHIFT_JIS := (string.Compare(TStringUtils.SHIFT_JIS,
    TStringUtils.PLATFORM_DEFAULT_ENCODING, true) = 0) or
    (string.Compare('EUC-JP', TStringUtils.PLATFORM_DEFAULT_ENCODING,
    true) = 0);
per: 
ASSUME_SHIFT_JIS := False;

**Comment by Spelt** [comment]
Is it involving Japanese?

2016-02-11 15:00 GMT+01:00 mrcarromesa <notifications@github.com>:

**Comment by mrcarromesa** [comment]
Sorry did not understand.

**Comment by Spelt** [comment]
What kind of language do you scan: japanese? 

Which localization do you have on your iphone? Or in which country do you live?

**Comment by mrcarromesa** [comment]
I live in Brazil,
I speak Portuguese.

**Comment by Spelt** [comment]
I will leave this open for a while. I tested this on IOS64 and IOS32 and there was not a problem here.

There was another problem though. An IOS32 crash on ITF barcodes. You need to update your source.

**Comment by mrcarromesa** [comment]
OK thank you!
