### ISSUE TITLE
Possible to generate a QR code from text

### ISSUE THREAD

**Issue by Chandlr** [Spelt/ZXing.Delphi#60]
Hi iam wondering how to generate a QR code from text using this library which is awesome 👍

**Comment by Spelt** [comment]
Hi

Thanks for the compliment.  This library focuses on decoding barcodes natively only because there wasnt any.  For encoding barcodes there was no need because there are other 3party solutions out there. 

Hope it helps!

**Comment by Spelt** [comment]
Forget to close.
