### ISSUE TITLE
GS1 Databar Family

### ISSUE THREAD

**Issue by toddbennett33704** [Spelt/ZXing.Delphi#61]

**Comment by toddbennett33704** [comment]
The ZXing barcode app supports the GS1 POS Databars (Omnidirectional, Stacked Omnidirectional, Expanded Stacked and Expanded). This wrapper does not have support for those yet. Any chance of updating this code to support GS1? Thanks!!!

**Comment by toddbennett33704** [comment]
[GS1_Barcodes_Fact_Sheet-GS1_DataBar_family.pdf](https://github.com/Spelt/ZXing.Delphi/files/1577437/GS1_Barcodes_Fact_Sheet-GS1_DataBar_family.pdf)

**Comment by Spelt** [comment]
Hi Todd,

Can you give me a link to the GS1 implementation in ZXing ?

Also ZXing.Delphi is not a wrapper but a full native implementation of the
ZXing lib.

Thanks, Edward





2017-12-21 1:18 GMT+01:00 toddbennett33704 <notifications@github.com>:

**Comment by Spelt** [comment]
I'd take a patch, but am not accepting feature requests. I did leave it open for a while to see if anyone wants to contribute it, but I am guessing you will have to implement this if you want it done.

**Comment by toddbennett33704** [comment]
Would you do it for a fee? If yes, how much would you charge?

Thanks!

**Comment by Spelt** [comment]
Dont have the time or urgency myself.

The .Net version here:
https://github.com/Redth/ZXing.Net/tree/3975188b7b0c806c9a8732cae921ed5e13a4b41b/Source/lib/oned/rss

The original source is here:
https://github.com/zxing/zxing/tree/master/core/src/main/java/com/google/zxing/oned/rss


The java version has some extra commits with some optimalizations.

Maybe somebody else can do it for a fee? Maybe you can post it here?
https://www.freelancer.com/post-project



2018-02-12 18:40 GMT+01:00 toddbennett33704 <notifications@github.com>:
