### ISSUE TITLE
Problem reading QR codes on iOS 11.2 64 bit devices

### ISSUE THREAD

**Issue by sdusik** [Spelt/ZXing.Delphi#62]
Hi
I am building an application which reads QR codes from cameras on Windows, Android and iOS devices. Everything is working fine on Windows, Android and iOS 10 (32 bit). There is a problem on 64 bit iOS 11.2 where no QR codes are read (1D codes are working fine).

I tried to trace, I found one problem here:
ZXing.QrCode.Internal.BitMatrixParser.pas  line  if (resultOffset <> version.TotalCodewords) 
resultOffset was different from version.TotalCodewords by number 1. Is there some possible rounding error? 

Thanks,

Stefan

**Comment by Spelt** [comment]
Hi Stefan

I will try to verify your findings this weekend.  I'll be in touch.



2018-01-04 16:02 GMT+01:00 sdusik <notifications@github.com>:

**Comment by Spelt** [comment]
Hi Stefan,

I just tested it with on an iPhone 8 with IOS 11.2.1 which is the latest and it just works with the QR Codes I used.

I used Delphi 10.2 update 2 to build the app. 


There were no problems detected.  Could you send me a QR barcode which is failing? 

Maybe I can help.


Edward

**Comment by sdusik** [comment]
Hi, thank you for your reply. Here is my QR Code.

[
![qr_platba_a_f](https://user-images.githubusercontent.com/29117719/34668788-2ce5b9b4-f46f-11e7-85ae-7f0feef984b3.png)
](url)

**Comment by Spelt** [comment]
Hi

Looks like this one is not working. 

I suspect that this is a type thing somewhere  in IOS64 like Int is uInt.  

Currently im a bit busy with other stuff so I cant really help you on the short term.

**Comment by sdusik** [comment]
Hi,

is any progress with that issue?

Thank you,

Stefan

**Comment by Spelt** [comment]
Did have to give the other issue report a priority over this one.

Can you try if you have the same bug with the latest v3.5?  Just to be sure
that it is still happening?









2018-02-13 8:32 GMT+01:00 sdusik <notifications@github.com>:

**Comment by sdusik** [comment]
Unfortunately it is still happening :-(

**Comment by Spelt** [comment]
In Rio 10.3.2. this is still occuring. 

For IOS 64, I recommend a native IOS Camera component which has build in QR code detection.  This is build in in the last major versions of IOS. Build in QR detection is pretty good, other codes are not so good.
In a commercial app I build I use both.

Issue will continue when there is a better debugger available.

**Comment by Spelt** [comment]
Its fixed in v3.9.0.

Android had the same problem.  See commit for details.
