### ISSUE TITLE
Keep getting a seqment fault in ZXing.Common.BitMatrix line 100 during debug

### ISSUE THREAD

**Issue by War3Evo** [Spelt/ZXing.Delphi#64]
First chance exception at $A2B58CB8. Exception class Segmentation fault (11). Process es.apk (11236)

Not a math expert, but during debugging on (Moto G Play) Android 6.0.1 (which is the only phone that debug works on) I get a Seqment Fault.  I'm not sure what else to do.  It happens 1 out of 3 times.

I'm only trying to read the bar code from food products.  Is there anyway I can bypass this error?

I'm using Delphi 10.2.2 Tokyo on Windows 10 Laptop with my Android phone plugged in USB.  I do have access to (Samsung S8) Android 7.0 and (Motorola Z2 Force) Android 8.0 devices but they wont let me debug on them.

function TBitMatrix.getBit(x, y: Integer): Boolean;
var
  offset, v, bits, shift: Integer;
  uBits: LongWord;
begin
  offset := y * FrowSize + TMathUtils.Asr(x, 5);
  try
    bits := Fbits[offset];   <<--------------------------------------- Red Line here
    uBits := LongWord(bits);
    shift := (x and $1F);
    v := TMathUtils.Asr(uBits, shift);
    Result := (v and 1) <> 0;
  except
    Result := false;
  end;

end;

**Comment by Spelt** [comment]
If I look look at the line it looks like an array is out of bounds. 

Is the error also happening on windows?

**Comment by War3Evo** [comment]
How could you prevent the array from going out of bounds?

I don't have a windows phone to test this on.  I just have Android Phones versions 6.0.1 , 7.0 , and 8.0.   I can only debug on 6.0.1 due to Android issues with Delphi and Debugging on the other versions/phones.

Not sure why the "Try" wouldn't just prevent the fault?


... I guess i'll play around with "limitations via SizeOf()" later.. if it doesn't get fixed.

**Comment by Spelt** [comment]
Hi

No I ment is it happening on windows too? (Not windows phone).  You can extend the unit test project with the barcode and test it there.

**Comment by Spelt** [comment]
Hi 
Is it possible that you answer the question? Is it also happening on Windows? You can test it with the VclTestApp which is in the solution.

**Comment by ChrisFieldhouse** [comment]
Hi
I also see this issue but only on iOS.  Everything works great on Windows and Android (at least for me).

When I last looked at this issue, it was that the index was massively higher than the bounds of the array.

If there's any extra info I can provide please let me know, otherwise keep up the good work.

Thanks

Chris

**Comment by Spelt** [comment]
Hoping for a better IOS64 debugger in the vNext.

**Comment by Spelt** [comment]
Can you check if this is still happening in v3.9.0 ?

It could be 64bit related.
