### ISSUE TITLE
QRCode, EAN8 and UPCE bar codes don't read

### ISSUE THREAD

**Issue by sboydlns** [Spelt/ZXing.Delphi#65]
It appears as though EAN8 and UPCE bar codes cannot be successfully read. Using VclTestApp any attempt to read either EAN8 or UPCE returns Unreadable!!

**Comment by sboydlns** [comment]
I'm also not having any luck reading QRCodes.

**Comment by sboydlns** [comment]
UPCA, EAN13, Code39 and Code128 seem to be working just fine.

**Comment by Spelt** [comment]
Hi can you post the barcodes? So I can take look.

**Comment by sboydlns** [comment]
I hope I'm attaching the file properly.

The file barall.tif contains a collection of test bar codes that came with a very old bar code reading SDK that I am looking to replace. The old SDK can read all bar codes on this page with no problem. ZXing.Delphi seems to be tripping over the EAN8 and UPCE bar codes. 

The file CC102092018.tif contains a collection of sample QR Codes that I found in a web page. This image was created by printing the web page and then scanning it as a black and white image @ 300DPI. Delphi.ZXIng doesn't seem to be able to recognize any of the QR Codes on this page. BTW, if I save one of the QR Code images from the web page to a PNG file, the QR Code can be read.

[TMP.zip](https://github.com/Spelt/ZXing.Delphi/files/1711357/TMP.zip)

**Comment by Spelt** [comment]
Yes I have the file.  I tested the QR page and they all worked with my app. 

The QR codes on the page are not the best quality  but it worked. I attached an image for proof.

**Comment by Spelt** [comment]
![unnamed](https://user-images.githubusercontent.com/12660181/36035113-484a6546-0db6-11e8-88da-4f118bad5f18.png)

**Comment by Spelt** [comment]
I did scanned it from the monitor (which is not always a good idea, depends on your scaling). The green rectangle is 'tracking' the code. Making a screenshot is not easy :-)

**Comment by sboydlns** [comment]
You seem to be doing this from a phone using a camera. I'm doing this on Windows using VclTestApp.exe to read the TIFF file. I need this to work in Windows to be useful.

**Comment by sboydlns** [comment]
BTW, I am using ZXing.Delphi 3.4.5 compiled with Delphi 10 (Berlin).

**Comment by Spelt** [comment]
I see what you mean. Im investigating.

**Comment by Spelt** [comment]
The QRCode bug was identified and fixed v3.5.   All QR Codes on the tiff are seperated and added to the unit test.  It all works now.  It also works via the vcl test app, 

Can you verify and report back?

**Comment by sboydlns** [comment]
The EAN8 and UPCE bar codes seem to be working. QRCode seems to work but only if there is just a single QRCode on the page. Attempting to read CC102092018.tif still fails. But if I modify that file by removing all but one QRCode it seems to work. I'm not sure if this is going to be a problem or not. I'm thinking not but only time will tell.

**Comment by Spelt** [comment]
Hi,

Yes, only one barcode per scan is supported.







2018-02-12 16:11 GMT+01:00 sboydlns <notifications@github.com>:
