### ISSUE TITLE
Code39 with check digit bug

### ISSUE THREAD

**Issue by sboydlns** [Spelt/ZXing.Delphi#66]
When trying to read a Code39 bar code with a check digit using the following:

`    hints := TDictionary<TDecodeHintType, TObject>.Create();
    hints.Add(TDecodeHintType.ASSUME_CODE_39_CHECK_DIGIT, nil);
    ScanManager := TScanManager.Create(TBarcodeFormat.CODE_39, hints);
`
the bar code is reported as unreadable.

This is due to a bug in TCode39Reader.decodeRow. The bit of code that verifies the check digit needs to be changed to:

`    if (self.decodeRowResult.Chars[max] <> ALPHABET_STRING[(total mod 43) + 1]) then
//    if (self.decodeRowResult.Chars[max] <> ALPHABET_STRING[total mod 43]) then
    begin
      Result := nil;
      exit
    end;

    self.decodeRowResult.Remove(max, self.decodeRowResult.length - max);
//    self.decodeRowResult.Remove(max, self.decodeRowResult.length);
`
The first change makes allowances for 1-based strings. The second gets rid of an exception caused when max + length exceeds the length of the string.

**Comment by Spelt** [comment]
Hi 
Thanks.  Can you add the barcode(s) as an image too?  So I can incorporate them in the unit tests.

**Comment by sboydlns** [comment]
In the zip file that I attached to this thread there is a file name BARALL.TIF. I contains a sample of a Code39 bar code with a check digit. This file also contains the samples of the EAN8 and UPCE bar codes that could not be read.

**Comment by Spelt** [comment]
In v3.5 all the barcodes in your example are added to the unit test and they all tested ok.  I also could read them with the VCL Test app. 

Can you verify and report back ?

**Comment by sboydlns** [comment]
Forgive me, but I'm kind of new to GIT. How do I get 3.5? Is it available via the download ZIP button?

**Comment by sboydlns** [comment]
The fix for the Code39 check digit doesn't seem to be in the latest. The scan still fails if you use the ASSUME_CODE_39_CHECK_DIGIT hint.
