### ISSUE TITLE
RGBLuminanceSource

### ISSUE THREAD

**Issue by bstsoftorg** [Spelt/ZXing.Delphi#7]
in RGBLuminanceSource.java
        if (r == g && g == b) {
          // Image is already greyscale, so pick any channel.
          luminances[offset + x] = (byte) r;
        } else {
          // Calculate luminance cheaply, favoring green.
          luminances[offset + x] = (byte) ((r + 2 * g + b) / 4);
        }
in RGBLuminanceSource.Pas
          luminances[offset + x] := red shl 16 or green shl 8 or blue;
need as
          if (red = green) and (green = blue)
            then luminances[offset + x] := red
            else luminances[offset + x] := ((red + 2 * green + blue) div 4);

**Comment by Spelt** [comment]
Can you explain a bit why this is better/faster?

Thanks

**Comment by bstsoftorg** [comment]
see  private final byte[] luminances;
(255+2*255+255)/4 always less than or equal to 255
    luminances: TArray<Byte>;
red shl 16 or green shl 8 or blue
255 shl 16 or 255 shl 8 or 255 = 16777215

I clearly explained? ;)

**Comment by bstsoftorg** [comment]
luminances: TArray(Byte);

**Comment by Spelt** [comment]
I will investigate this. Problem could be debugging and comparing results (arrays, vars etc etc) with the original source.  
Its already almost 20x times faster then the .NET source (Code 128 anyway).  Guess thats because of the generics array (the original use classic arrays) use I introduced and massive bit shifting.  

PS you need to do an update because of a IOS32 bug fix.

**Comment by bstsoftorg** [comment]
Thank you so much for your work. But I had to give up your project over a month ago. Reasons:
1.work on XE4 and I have some code to constantly adjust after the update you can.
2.don't use FreeMonky (need pure pascal text for compatibility).
3.my supposed working in Lazarus and Delphi. Use Delphi to compile Intel x86. Lazarus for Raspberi Pi 2
4.I needed the EAN, 39, 128, and PDF417.
ps. PDF417 I had to learn from scratch and now I know, even with the camera. With the possibility of rotation (auto determination of the angle reversal of the image). For work and one written in Delphi XE7, XE8, 10 need to buy a license. If there would be funding, I would have ported the code of PDF417, which I had to write on "C" in "Delphi".

**Comment by Spelt** [comment]
Ok thanks for the information. I clearly understand the Raspberi Pi 2
thing.

2016-02-22 5:58 GMT+01:00 bstsoftorg <notifications@github.com>:

**Comment by Spelt** [comment]
See: https://github.com/Spelt/ZXing.Delphi/issues/18
