### ISSUE TITLE
Sony Xperia camera problem

### ISSUE THREAD

**Issue by bigjuice** [Spelt/ZXing.Delphi#72]
Hi,

I run your app on my Google Pixel (Android 8 and 9) and everything is perfect. I try to run it on another phone, Sony Xperia (Android 5.1.1), but when I try to start capture I got an error.

Here is the message I got from Delphi debugger : "Project expedition.apk raised exception class Aborted (6)."

The error occurs when I set the "camera.Active := True"

I continue my research, but if you have any ideas that can help me...
Little upgrade : I use the sample camera project from Embarcadero, the camera was working. But when I try to use the carema tweak, I got the same error.

Thank you very much :)
I really love your app.

**Comment by Spelt** [comment]
Hi

Thanks. Does the camera work isolated without the scan lib?

There is also a simplified camera component which does basically the same thing. You can try it to isolate te problem. You can find it here: https://bitbucket.org/gmurt/kscomponents <https://bitbucket.org/gmurt/kscomponents> 

Hope it help!

**Comment by bigjuice** [comment]
Hi Spelt,

As I say, I use the sample camera project from Embarcadero, the camera was working. But when I try to use the carema tweak, I got the same error.

I will try the the kscomponents today.

Thank you,

**Comment by bigjuice** [comment]
Hi to everyone,

I tried others phones. I already use it on my Google Pixel (android 9.0) and everything works fine.

I try Samsung Galaxy S6 (android 6.0.1) and everything works fine.

I try Sony Xperia Z Ultra (android 5.1.1) NOT WORKING.

I try Sony Xperia Z5 Premium (android 7.1.1) NOT WORKING.

The problem is the same, when I try to open the camera the app crash.

Thank you for your help,
bigjuice

**Comment by Spelt** [comment]
Hi bigJuice

Its a camera issue and it related only when you have installed the camera patch?

Do you think its an Android 5.1.1 and 7.1.1 issue?

If you step into it with break points can you identify which line it breaks?

**Comment by bigjuice** [comment]
Hi Spelt,

I didn't find where was the problem exactly. But I found a solution from another github place.

I take the camera tweak from this place and everything fine.  I saw that you comment this project.
https://github.com/zhaoyipeng/DelphiDemos

I have not looked at the code to see the difference.

Thank you for your help.

**Comment by Spelt** [comment]
No problem.

Awesome that the camera is fine too
