### ISSUE TITLE
Cannot read any QR code in iOS 12

### ISSUE THREAD

**Issue by kdevil88** [Spelt/ZXing.Delphi#74]
Hi,
Developing RadStudio XE 10.2.3 (Tokyo) + Android\iOS app with the ability to scan QR codes.
Everything works fine for me in Android, but in iOS 12 (xcode 9.3)  none of readers could decode image.
Also tried to resize image to smaller res (e.g. 640x480) with no effect.
Any idea? Thanks.

**Comment by Spelt** [comment]
Hi

Did you build it for IOS12 or IOS 11? And then deployed it for IOS12?

Thanks

**Comment by kdevil88** [comment]
> Hi Did you build it for IOS12 or IOS 11? And then deployed it for IOS12? Thanks
> […](#)
> Op 21 nov. 2018 om 17:04 heeft kdevil88 ***@***.***> het volgende geschreven: Hi, Developing RadStudio XE 10.2.3 (Tokyo) + Android\iOS app with the ability to scan QR codes. Everything works fine for me in Android, but in iOS 12 (xcode 9.3) none of readers could decode image. Also tried to resize image to smaller res (e.g. 640x480) with no effect. Any idea? Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Built with ios 11.3 sdk, deployed to ios 12

**Comment by Spelt** [comment]
Best is then to wait when Delphi supports IOS 12. 

You can apply for the beta if you have a subscription.

**Comment by kdevil88** [comment]
> Best is then to wait when Delphi supports IOS 12.
> 
> You can apply for the beta if you have a subscription.

Thanks, probably waiting for 10.3 is the only thing that remains, neither zxing nor zbar not working on IOS for me..

**Comment by kdevil88** [comment]
> Best is then to wait when Delphi supports IOS 12. You can apply for the beta if you have a subscription.
> […](#)
> Op 21 nov. 2018 om 18:06 heeft kdevil88 ***@***.***> het volgende geschreven: Hi Did you build it for IOS12 or IOS 11? And then deployed it for IOS12? Thanks … Op 21 nov. 2018 om 17:04 heeft kdevil88 ***@***.***> het volgende geschreven: Hi, Developing RadStudio XE 10.2.3 (Tokyo) + Android\iOS app with the ability to scan QR codes. Everything works fine for me in Android, but in iOS 12 (xcode 9.3) none of readers could decode image. Also tried to resize image to smaller res (e.g. 640x480) with no effect. Any idea? Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. Built with ios 11.3 sdk, deployed to ios 12 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Installed today rad studio 10.3 (not beta) + xcode 10.1 + ios 12 sdk, problem remains, no result in ios.. :(
P.s: in Android (rad studio 10.3) processmessages not working, so better rollback..

**Comment by Spelt** [comment]
Hi
I installed Rio, IOS 12 on my IPhone 8, Mojave with updates and I have no issues or problems scanning QRCodes with the library. 

There must be something else going on.

**Comment by kdevil88** [comment]
Hi, i’m uisung macos on vmware and have no ability to debug ios apps, cannot watch where it fails to scan.
VMware may be a reason of my issue too..
Do you use vmware or physical device?

**Comment by Spelt** [comment]
I dont think vmware is the issue.   Debugging should be possible.  I use a pc and a mac seperatly, both physically.

**Comment by kdevil88** [comment]
Watched this topic https://forums.embarcadero.com/thread.jspa?threadID=279888 and nothing helps, same error.
However, no way to determine why scanning barcodes not working for me on iOS.
As workaround we put barcode scanning to backend.
In any case - thanks for reaction :)

**Comment by Spelt** [comment]
Thats funny , thats me replying in that thread.  
I did got the same problem.  Its a region and languge setting issue.
