### ISSUE TITLE
error: cannot find -lfastutils-android

### ISSUE THREAD

**Issue by fredycc** [Spelt/ZXing.Delphi#76]
I'm experiencing an error related specifically to the demo: FmxAdvancedTestApp.dproj

> [DCC Error] E2597 C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-ndk-r9c\toolchains\arm-linux-androideabi-4.6\prebuilt\windows\bin\arm-linux-androideabi-ld.exe: error: cannot find -lfastutils-android
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-ndk-r9c\toolchains\arm-linux-androideabi-4.6\prebuilt\windows\bin\arm-linux-androideabi-ld.exe: C:\Users\Me\Downloads\ZXing.Delphi-3.6\demo\advancedTestApp\Android\Release\FastUtils.o: in function Fastutils::yv12_to_rgba(void*, void*, void*, void*, int, int, int, int, int):FastUtils(.text._ZN9Fastutils12yv12_to_rgbaEPvS0_S0_S0_iiiii+0x2e): error: undefined reference to '_yv12_to_rgba'
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-ndk-r9c\toolchains\arm-linux-androideabi-4.6\prebuilt\windows\bin\arm-linux-androideabi-ld.exe: C:\Users\Me\Downloads\ZXing.Delphi-3.6\demo\advancedTestApp\Android\Release\FastUtils.o: in function Fastutils::RotateBitmap90Degrees(void*, void*, int, int):FastUtils(.text._ZN9Fastutils21RotateBitmap90DegreesEPvS0_ii+0x4): error: undefined reference to '_rotate_90'
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-ndk-r9c\toolchains\arm-linux-androideabi-4.6\prebuilt\windows\bin\arm-linux-androideabi-ld.exe: C:\Users\Me\Downloads\ZXing.Delphi-3.6\demo\advancedTestApp\Android\Release\FastUtils.o: in function Fastutils::RotateBitmap180Degrees(void*, void*, int, int):FastUtils(.text._ZN9Fastutils22RotateBitmap180DegreesEPvS0_ii+0x4): error: undefined reference to '_rotate_180'
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-ndk-r9c\toolchains\arm-linux-androideabi-4.6\prebuilt\windows\bin\arm-linux-androideabi-ld.exe: C:\Users\Me\Downloads\ZXing.Delphi-3.6\demo\advancedTestApp\Android\Release\FastUtils.o: in function Fastutils::RotateBitmap270Degrees(void*, void*, int, int):FastUtils(.text._ZN9Fastutils22RotateBitmap270DegreesEPvS0_ii+0x4): error: undefined reference to '_rotate_270'

I have installed the jdk-8u172 and the Rio Community version.

I can compile other demos without problem, I hope you can support me.

Thank you

**Comment by Spelt** [comment]
Hi fredy

I’m currently without a pc but my guess is that you need to set some project paths correctly.  There is a readme somwhere which explains it. 

The advanced camera demo makes use of a camera hack for improved camera performance.  

Let us know if it helps!

Edward

**Comment by fredycc** [comment]
thanks to your comment I can notice that 2 additional libraries are needed that are used in FastUtils.pas

- \demo\advancedTestApp\SIMD \libfastutils.a
- \demo\advancedTestApp\ SIMD\libfastutils-android.a

I was able to find them in another repository: 

> https://github.com/zhaoyipeng/DelphiDemos/tree/master/ScanCodeDemo/SIMD

I just copied them into **SIMD** and it worked.

Thanks again

**Comment by Spelt** [comment]
They should be also there in this repo.  I’ll check.
