### ISSUE TITLE
AdvancedTestApp Rio

### ISSUE THREAD

**Issue by marcogps** [Spelt/ZXing.Delphi#78]
Is not working perfomance units in the Delphi 10.3 release, could you see what the problem is?

**Comment by narkoKast** [comment]
Only crash ...

**Comment by flydev-fr** [comment]
@narkoKast  Working here, see the screenshot from the mobile (Samsung J5 / Android 8.1 / Rio 10.3)

![screenshot_20181228-112543](https://user-images.githubusercontent.com/11658616/50512701-d31eeb80-0a93-11e9-8855-a4e058d6aa04.png)

**Comment by marcogps** [comment]
Probably not using an FMX.media.android drive for fps gain. As image is 3.4 fps, the problem occurs when you use it.

**Comment by flydev-fr** [comment]
With a resolution of 720x480 i got ~15fps. The screenshot is taken with a resolution of 1280x720.

**Comment by Spelt** [comment]
Way to slow.

I'll try to fix the Advanced app. I've heard that are some units missing.





Op vr 28 dec. 2018 om 12:57 schreef flydev <notifications@github.com>:

**Comment by Spelt** [comment]
You should have a stable 29/30 fps



Op vr 28 dec. 2018 om 13:00 schreef Edward Spelt <edwardspelt@gmail.com>:

**Comment by flydev-fr** [comment]
Compiling with `FastUtils.pas` from `Fast` folder, I got 25,1fps with a resolution of 720x480, which is quite acceptable 👍 

![25fps](https://user-images.githubusercontent.com/11658616/50517646-8d711b80-0ab1-11e9-891c-0aa2f1940d9a.jpg)

**Comment by marcogps** [comment]
@flydev-fr  Could you make this project available for download?

**Comment by flydev-fr** [comment]
@marcogps yes, I was going to do so once back at home. wait an hour or so.

**Comment by flydev-fr** [comment]
There you can grab the project :  https://github.com/flydev-fr/ZXing.Test

**Comment by narkoKast** [comment]
I have checked new demo (Delphi RIO, phone: Android 6.0,  LG-H815)
If make scan ON I get debugger "FmxAdvancedTestApp.apk raised exception class illegal instruction(4)" and app crashed. If only change Resolution also get the same exception immediately.

**Comment by Spelt** [comment]
Hi. Unfortunately there is an incompatibility somewhere in the fastlib.o files.  I updated the home page: 
https://github.com/Spelt/ZXing.Delphi  if there is a change to the situation I'll post an update.

**Comment by Spelt** [comment]
Hi all,

The problem is solved.  The camera on Android is good again. 

Download now your update. 

Let us know your result!

**Comment by flydev-fr** [comment]
Thanks, I saw the message from E. van Bilsen and tested it this afternoon, it works great !

**Comment by 372235** [comment]
When I turn on the camera and return to ZXingAPP, There was a mistake.
like This:
![ ](https://github.com/372235/error/blob/master/webwxgetmsgimg.jpg?raw=true)

**Comment by marcogps** [comment]
It was excellent with the stitching done. It is not running at 30 fps, but at a lower resolution such as 640x480 it is around 21 fps

Thank you

**Comment by flydev-fr** [comment]
A test with a resolution of 1280x720 give me 26/30 fps 👍   


![real-screen image](https://github.com/flydev-fr/ZXing.Test/raw/master/docs/real-screen.png)
