### ISSUE TITLE
on Android device have a mistake

### ISSUE THREAD

**Issue by 372235** [Spelt/ZXing.Delphi#79]
When I turn on the camera and return to ZXingAPP, There was a mistake.Android device version6.01,the mistake only in AdvancedTestApp,other test is OK.
like This:
![ ](https://github.com/372235/error/blob/master/webwxgetmsgimg.jpg?raw=true)

**Comment by Spelt** [comment]
No good reproduction case provided.

**Comment by 372235** [comment]
> No good reproduction case provided.

Error Tips:
Java.langRuntimeException:
getParameters failed(empty parameters)
