### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by Kline777** [Spelt/ZXing.Delphi#8]
Hi!
I am trying to setup a form with the windows camera on, detecting QRCodes on threads on real time.

It was really easy to do but the problem was when i run a memory leak profiler and the code is (according to the profiler) really missing a lot of Destroy() statments.
I've also seen large peaks of memory consumed that was not properly release.

Is this normal? Am i doing something stupid? :p

**Comment by Spelt** [comment]
HI

Most of destroy methods are not needed because of Firemonkey and ARC. 

Do you run as a firemonkey application or as VCL?

Which memory profiler did you use?

**Comment by Kline777** [comment]
Yeah.. i assumed that also, but the truth is that i've seen a lot of memory peaks and the system slowing down.

Firemonkey XE3, using Madexcept

**Comment by Kline777** [comment]
I have the camera running and a thread launched every 100ms to process the current frame
After a couple of seconds the memory of the app raises and the all thing slows down.

Then i used madexcept, and add a couple of destroy statments and it was ok, but i could work 100% of them.

I am using this on Windows.

**Comment by Spelt** [comment]
And if you wait for a frame scan to finish before you do the next one?

**Comment by Kline777** [comment]
In the previous post i meant 'Couldnt solve 100% of the memory leaks' it started ok but the last one affect the stability of the code. Is a lot of code to cover and i may destroy some objects before time.

I will try that. Thank you for your quick responses ;)

**Comment by Kline777** [comment]
Hum.. its the same. I'm using a version with a couple of destroy staments that solve must of the memory peaks and now its seems ok. Have you used this component in a firemonkey for windows application with a lot of scans?

Maybe its not the best indicator but the memory of the application in the Task Manager goes up like 0.3MB for each scan call.

**Comment by Spelt** [comment]
It looks  like something in statics. I'll fix this. 



Verstuurd vanaf mijn iPad

**Comment by Spelt** [comment]
I took the time and did some investigation and I think I fixed it. 

Could you give it a try ? And let me know?

**Comment by RZ75** [comment]
Just compiled and tested with aTestApp and with ReportMemoryLeaksOnShutDown := true running in Win32 FMX.

Following Leaks were reported only with camera on / off and closing the application:
13-20 bytes: TBitArray x 135
45-52 bytes: TList<FMX.Content.DX9.TCustomDX9Context> x 1, Unknown x 135
149-156 bytes: Unknown x 135

**Comment by Spelt** [comment]
Ok thanks. Is it nil?

**Comment by Spelt** [comment]
Thats the test app not freeing the reader?

**Comment by RZ75** [comment]
Yes, thats the test app.

**Comment by Spelt** [comment]
I merged the pull request that was causing an exception. 

@Cline: about your ARC question. Firemonkey for Windows does not have Arc. When an object is created and gets out of scope (no references to it) it will be freed.

See:
http://stackoverflow.com/questions/27818697/how-to-free-a-component-in-android-ios

Im going to close this issue and open another: test project leak
