### ISSUE TITLE
Problem reading QR codes on windows

### ISSUE THREAD

**Issue by Beanv587** [Spelt/ZXing.Delphi#80]
hello
I tried to scan this images,but nothing result. 
I tried to change the size of the image.  Zoom in 100% or zoom out 50% can solve the problem

![qr_problem1](https://user-images.githubusercontent.com/30143806/52531659-97926500-2d53-11e9-8663-8625de56040b.jpg)

**Comment by Beanv587** [comment]
I went to zxing.org[https://zxing.org/w/decode.jspx](url)  to uploaded this image and found that it can be decoded correctly.

**Comment by Spelt** [comment]
Hi Bean,

I just tested it with our app but it just works. 

It must be something else.

**Comment by Beanv587** [comment]
Hi Spelt,

You can use demo\vclTestApp to tested it,it returns Unreadable

![xx](https://user-images.githubusercontent.com/30143806/52543720-b988f780-2de6-11e9-98c3-21b4b786ad77.jpg)

**Comment by Beanv587** [comment]
My delphi version is 10.2

**Comment by Spelt** [comment]
Hi

I tested it with Rio (should not make a difference) and IOS64.

Hope to look into it this week.

**Comment by Beanv587** [comment]
ok tks

**Comment by Spelt** [comment]
Well, not a bug :-)

I did find the time to check it out more and this is what I found:

The barcode needs the flag: PURE_BARCODE  see for flags:
https://zxing.github.io/zxing/apidocs/com/google/zxing/DecodeHintType.html

It is probably a pure monochrome image which is probably a special kind.

It works if you add the flag with the decoding like in the DUnitXTest:



procedure TZXingDelphiTest.All_PURE_QRCode();
var
result: TReadResult;
hints: TDictionary<TDecodeHintType, TObject>;
begin

try

hints := TDictionary<TDecodeHintType, TObject>.Create();
hints.Add(TDecodeHintType.PURE_BARCODE, nil);


    result := Decode('beantest.jpg', TBarcodeFormat.QR_CODE, hints);
Assert.IsNotNull(result, ' Nil result ');
Assert.IsTrue(result.Text.Contains('ivaservizi.'),
'QR code result Text Incorrect: ' + result.Text);


etc












Op ma 11 feb. 2019 om 14:05 schreef Beanv587 <notifications@github.com>:

**Comment by Beanv587** [comment]
Thank you very mutch!
