### ISSUE TITLE
Useless assignment?

### ISSUE THREAD

**Issue by csm101** [Spelt/ZXing.Delphi#82]
Hi, I just noticed this strange assignment within  ZXing.QrCode.Internal.FinderPatternImplementation.pas:

    function TFinderPattern.aboutEquals(const moduleSize, i, j: Single): Boolean;
    var
      moduleSizeDiff : Single;
    begin
      Result := false;
      
      x := Self.x; //  <-- Why are we doing this?
      y := Self.y; //  <-- Why are we doing this?
    
      if ((Abs(i - self.y) <= moduleSize) and (Abs(j - self.x) <= moduleSize)) then
      begin
        moduleSizeDiff := Abs(moduleSize - self.estimatedModuleSize);
    
        Result := ((moduleSizeDiff <= 1) or
           (moduleSizeDiff <= self.estimatedModuleSize));
      end;
    end;

It looks like we are assigning self.x and self.y to themselves. Do those two lines actually do something useful?

**Comment by Spelt** [comment]
Your'e right. It does nothing at all. I cleaned it up.



Thanks Carlo!



Op ma 18 feb. 2019 om 16:35 schreef Carlo Sirna <notifications@github.com>:
