### ISSUE TITLE
Error Tips

### ISSUE THREAD

**Issue by 372235** [Spelt/ZXing.Delphi#83]
No good reproduction case provided.

_Originally posted by @Spelt in https://github.com/Spelt/ZXing.Delphi/issues/79#issuecomment-466779958_

When I turn on the camera and return to ZXingAPP, There was a mistake.Android device version6.01,the mistake only in AdvancedTestApp,other test is OK.
like This:
https://github.com/372235/error/blob/master/webwxgetmsgimg.jpg?raw=true
Error Tips:
Java.langRuntimeException:
getParameters failed(empty parameters)

**Comment by entratel** [comment]
I've the same trouble on an android 7 device, using delphi Rio 10.3.1, with the FMXTestApp.
When the start camera button is pushed the enclosed error is issued.
![IMG_20190406_120435](https://user-images.githubusercontent.com/29211465/55668067-aafa1200-5864-11e9-96a7-c15cab21a9fa.jpg)
Launching the FMXAdvancedTestApp doesn't start. I see only the splashscreen.

**Comment by Spelt** [comment]
Probably the new Android security feature. 

Does the camera demo from Embarcadero work?

**Comment by entratel** [comment]
Permissions have been setted.
Yes the camera demo from Embarcadero is working.

**Comment by 372235** [comment]
when camera not close it will be happened,
when camera change (front to back)or(back to front) is working.the Error vanished.
It seems that the thread has not ended.

**Comment by 372235** [comment]
It seems that the thread has not ended.

**Comment by entratel** [comment]
I've tested further on other devices with different android versions.
On Android 5 and 9 it's running well, the error is issued on android 7 on a device with a low resolution camera.

**Comment by Spelt** [comment]
Too vague.
