### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by drum77** [Spelt/ZXing.Delphi#84]
Memory Leak in ZXing.Datamatrix.Internal.Detector.pas line 374

 l1 := (Abs((dimensionTop - transitionsBetween(topLeft, c1).Transitions)) +
    Abs((dimensionRight - transitionsBetween(bottomRight, c1).Transitions)));
  l2 := (Abs((dimensionTop - transitionsBetween(topLeft, c2).Transitions)) +
    Abs((dimensionRight - transitionsBetween(bottomRight, c2).Transitions)));

object TResultPointsAndTransitions not free

**Comment by drum77** [comment]
Memory Leak in ZXing.Datamatrix.Internal.Decoder.pas line 163

    // Error-correct and copy data blocks together into a stream of bytes
    for j := 0 to Pred(dataBlocksCount) do
    begin
      DataBlock := dataBlocks[j];
      codewordBytes := DataBlock.codewords;
      numDataCodewords := DataBlock.numDataCodewords;
      if (not correctErrors(codewordBytes, numDataCodewords)) then
      begin
        Result := nil;
        exit;
      end;
      for i := 0 to Pred(numDataCodewords) do
      begin
        // De-interlace data blocks.
        resultBytes[(i * dataBlocksCount) + j] := codewordBytes[i];
      end;

      DataBlock.Free;
    end;


exit and dataBlocks not free

**Comment by Spelt** [comment]
Hi

Is this for all datamtrix codes?  Can you otherwise add a barcode to the issue? A failing case?


Thanks!

**Comment by matteopasini** [comment]
Hi,
I've had the same problem while reading a qrcode. I solved it by adding a free to DataBlock inside the function TDataMatrixDecoder.decode, and assigning the result of  transitionsBetween() on line 374 of ZXing.Datamatrix.Internal.Detector.pas to a var and adding  a free after the  execution.

**Comment by drum77** [comment]
thx
  

 

 ------------------ 原始邮件 ------------------
  发件人: "matteopasini"<notifications@github.com>;
 发送时间: 2019年8月12日(星期一) 晚上6:55
 收件人: "Spelt/ZXing.Delphi"<ZXing.Delphi@noreply.github.com>;
 抄送: "楼屈屈"<1816220978@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [Spelt/ZXing.Delphi] Memory Leak (#84)

 

 
Hi,
I've had the same problem while reading a qrcode. I solved it by adding a free to DataBlock inside the function TDataMatrixDecoder.decode, and assigning the result of transitionsBetween() on line 374 of ZXing.Datamatrix.Internal.Detector.pas to a var and adding a free after the execution.
