### ISSUE TITLE
Issue on reacquiring camera access in Android

### ISSUE THREAD

**Issue by keelea** [Spelt/ZXing.Delphi#85]
This issue looks to be present only in the advancedTestApp. When the user minimizes the app thereby invoking StopCapture in the EnteredBackground event, there seems to be a 1 minute window where the camera can be started again after bringing the app out of the background and back into focus. After 1 minute it throws an exception:

java.lang.RuntimeException: getParameters failed (empty parameters)

**Comment by iwan-c-sugeng** [comment]
I've just read your problem, see my comment, it has the same problem and i found the solution

**Comment by Spelt** [comment]
Thanx guys!

I’ll try to update it this weekend.
