### ISSUE TITLE
can you make the software Generate Barcode images

### ISSUE THREAD

**Issue by RaySa74** [Spelt/ZXing.Delphi#87]
thanks for your work

can you please make ZXing.Delphi Generate Barcode images, where you give ZXing.Delphi a barcode number and ZXing.Delphi Generates a barcode image.

thanks

**Comment by Spelt** [comment]
Hi Ray,

There are no plans for that. There are probably 3party libs out there who
can already do this perfectly.

Sincerely,
Edward


Op zo 18 aug. 2019 om 13:36 schreef RaySa74 <notifications@github.com>:
