### ISSUE TITLE
Build error when compiling to IOS device

### ISSUE THREAD

**Issue by RaySa74** [Spelt/ZXing.Delphi#88]
When try to run the application (FmxAdvancedTestApp) on IOS Device I get this error [DCC Error] E2597 ld: file not found: libfastutils.a
I tried to find the file but it’s not in the folders ??
Please help
thanks

**Comment by Spelt** [comment]
The project needs to have a special project folder configuration.

**Comment by RaySa74** [comment]
Thanks for the quick reply, great work.
Can you please be more specific on how to do the special project folder configuration for IOS. So that it will eliminate the file not found: libfastutils.a error .
Thanks again

**Comment by Spelt** [comment]
I think there is a readme or some explaination in the pas file i think.  

Sorry im doing this from a phone now

**Comment by RaySa74** [comment]
the file ibfastutils.a is missing from the SIMD folder in version v3.8.3. i downloaded the file from version V3.4.3 and copied it the the SIMD for v3.8.3. and the error stop showing up ! but now  i am getting [DCC Fatal Error] F2588 Linker error code: 3221225477 ($c0000005) when i try to run it on my ios device??? please help

Checking project dependencies...
Building FmxAdvancedTestApp.dproj (Debug, iOSDevice64)
brcc32 command line for "FmxAdvancedTestApp.vrc"
  f:\program files (x86)\embarcadero\studio\20.0\bin\cgrc.exe -c65001 "FmxAdvancedTestApp.vrc" -foFmxAdvancedTestApp.res 
dcciosarm64 command line for "FmxAdvancedTestApp.dpr"
  f:\program files (x86)\embarcadero\studio\20.0\bin\dcciosarm64.exe -$O- --no-config -B -Q -AGenerics.Collections=System.Generics.Collections;
  Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG 
  -E.\iOSDevice64\Debug -I"f:\program files (x86)\embarcadero\studio\20.0\lib\iOSDevice64\debug";simd;custom;..\..\Lib\Classes;..\..\Lib\Classes\Common;
  ..\..\Lib\Classes\Common\Detector;..\..\Lib\Classes\Common\ReedSolomon;..\..\Lib\Classes\Filtering;"..\..\Lib\Classes\1D Barcodes";
  "..\..\Lib\Classes\2D Barcodes";"..\..\Lib\Classes\2D Barcodes\Decoder";"..\..\Lib\Classes\2D Barcodes\Detector";"f:\program files 
  (x86)\embarcadero\studio\20.0\lib\iOSDevice64\Release";C:\Users\Public\Documents\RTLPackages\FMXRTL\D103Rio\iOSDevice64\Release 
  -LEC:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\iOSDevice64 -LNC:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\iOSDevice64 
  -NU.\iOSDevice64\Debug -NSSystem;Xml;Data;Datasnap;Web;Soap; -Osimd;custom;..\..\Lib\Classes;..\..\Lib\Classes\Common;
  ..\..\Lib\Classes\Common\Detector;..\..\Lib\Classes\Common\ReedSolomon;..\..\Lib\Classes\Filtering;"..\..\Lib\Classes\1D Barcodes";
  "..\..\Lib\Classes\2D Barcodes";"..\..\Lib\Classes\2D Barcodes\Decoder";"..\..\Lib\Classes\2D Barcodes\Detector";"f:\program files 
  (x86)\embarcadero\studio\20.0\lib\iOSDevice64\Release";C:\Users\Public\Documents\RTLPackages\FMXRTL\D103Rio\iOSDevice64\Release -Rsimd;custom;
  ..\..\Lib\Classes;..\..\Lib\Classes\Common;..\..\Lib\Classes\Common\Detector;..\..\Lib\Classes\Common\ReedSolomon;..\..\Lib\Classes\Filtering;
  "..\..\Lib\Classes\1D Barcodes";"..\..\Lib\Classes\2D Barcodes";"..\..\Lib\Classes\2D Barcodes\Decoder";"..\..\Lib\Classes\2D Barcodes\Detector";
  "f:\program files (x86)\embarcadero\studio\20.0\lib\iOSDevice64\Release";C:\Users\Public\Documents\RTLPackages\FMXRTL\D103Rio\iOSDevice64\Release 
  -U"f:\program files (x86)\embarcadero\studio\20.0\lib\iOSDevice64\debug";simd;custom;..\..\Lib\Classes;..\..\Lib\Classes\Common;
  ..\..\Lib\Classes\Common\Detector;..\..\Lib\Classes\Common\ReedSolomon;..\..\Lib\Classes\Filtering;"..\..\Lib\Classes\1D Barcodes";
  "..\..\Lib\Classes\2D Barcodes";"..\..\Lib\Classes\2D Barcodes\Decoder";"..\..\Lib\Classes\2D Barcodes\Detector";"f:\program files 
  (x86)\embarcadero\studio\20.0\lib\iOSDevice64\Release";C:\Users\Public\Documents\RTLPackages\FMXRTL\D103Rio\iOSDevice64\Release 
  --syslibroot:C:\Users\Daddy\Documents\Embarcadero\Studio\SDKs\iPhoneOS11.0.sdk 
  --frameworkpath:C:\Users\Daddy\Documents\Embarcadero\Studio\SDKs\iPhoneOS11.0.sdk\System\Library\Frameworks;
  C:\Users\Daddy\Documents\Embarcadero\Studio\SDKs\iPhoneOS11.0.sdk\System\Library\PrivateFrameworks -V -VN --linker-option:"-arch arm64" 
  -NO.\iOSDevice64\Debug  FmxAdvancedTestApp.dpr   
[DCC Hint] ZXing.Common.BitArrayImplementation.pas(383): H2077 Value assigned to 'TBitArrayImplementation.isRange' never used
[DCC Hint] ZXing.QrCode.Internal.Version.pas(188): H2593 Code has no effect. Compiler generated temporary variable is cleared instead
[DCC Hint] ZXing.QrCode.Internal.Version.pas(191): H2593 Code has no effect. Compiler generated temporary variable is cleared instead
[DCC Hint] ZXing.QrCode.Internal.Version.pas(665): H2593 Code has no effect. Compiler generated temporary variable is cleared instead
[DCC Hint] ZXing.QrCode.Internal.DataMask.pas(135): H2593 Code has no effect. Compiler generated temporary variable is cleared instead
[DCC Hint] ZXing.QrCode.Internal.Decoder.pas(272): H2593 Code has no effect. Compiler generated temporary variable is cleared instead
[DCC Hint] ZXing.QrCode.Internal.FinderPatternFinder.pas(515): H2077 Value assigned to 'pureBarcode' never used
[DCC Hint] ZXing.Datamatrix.Internal.Version.pas(162): H2593 Code has no effect. Compiler generated temporary variable is cleared instead
[DCC Warning] AudioManager.pas(45): W1000 Symbol 'TList' is deprecated: 'Use System.Generics.Collections.TList<T>'
[DCC Warning] AudioManager.pas(45): W1000 Symbol 'TList' is deprecated: 'Use System.Generics.Collections.TList<T>'
[DCC Warning] AudioManager.pas(93): W1000 Symbol 'TList' is deprecated: 'Use System.Generics.Collections.TList<T>'
[DCC Warning] AudioManager.pas(111): W1000 Symbol 'Count' is deprecated
[DCC Warning] AudioManager.pas(115): W1000 Symbol 'Delete' is deprecated
[DCC Warning] AudioManager.pas(162): W1000 Symbol 'Add' is deprecated
[DCC Hint] AudioManager.pas(145): H2077 Value assigned to 'TAudioManager.AddSound' never used
[DCC Hint] AudioManager.pas(141): H2164 Variable 'wCFRunLoopRef' is declared but never used in 'TAudioManager.AddSound'
[DCC Hint] AudioManager.pas(142): H2164 Variable 'winRunLoopMode' is declared but never used in 'TAudioManager.AddSound'
[DCC Warning] AudioManager.pas(173): W1000 Symbol 'Count' is deprecated
[DCC Warning] AudioManager.pas(183): W1000 Symbol 'Delete' is deprecated
[DCC Warning] AudioManager.pas(195): W1000 Symbol 'Count' is deprecated
[DCC Warning] AudioManager.pas(224): W1000 Symbol 'Count' is deprecated
[DCC Warning] AudioManager.pas(265): W1000 Symbol 'Count' is deprecated
[DCC Warning] AudioManager.pas(281): W1000 Symbol 'Count' is deprecated
[DCC Warning] AudioManager.pas(286): W1000 Symbol 'Count' is deprecated
[DCC Warning] uMain.pas(259): W1035 Return value of function 'TFormMain.AppEvent' might be undefined
[DCC Hint] uMain.pas(120): H2219 Private symbol 'FCaptureSettings' declared but never used
[DCC Hint] uMain.pas(121): H2219 Private symbol 'targetRect' declared but never used
[DCC Fatal Error] F2588 Linker error code: 3221225477 ($c0000005)
Failed
Elapsed time: 00:00:19.2

**Comment by Spelt** [comment]
Linker error is sometimes cleared by ‘clean’ from right click on project. 

The project makes use of an advanced camera hack.

**Comment by zzzxtreme** [comment]
have you found solution to this? I'm getting the exact linker code and I am using libfastutil and zxing

**Comment by Spelt** [comment]
I did a clean all and a rebuild and then it worked. It was on rio 3.2 I think.

**Comment by LoneStarS4** [comment]
I still get the exact same linker error when building for Debug even after clean. For release builds there are no errors. I use Delphi 10.3 Update 3 and try to build for iPhone OS 13.2. Any ideas?

**Comment by Spelt** [comment]
Is this the demo app?

**Comment by LoneStarS4** [comment]
It is the FmxAdvancedTestApp and also in an app I created myself

**Comment by Spelt** [comment]
Sounds like it does not find or is linking in the external lib what is needed.
