### ISSUE TITLE
Error compiling FmxAddvancedTestApp - Delphi 10.3.3 (Android 64-bit)

### ISSUE THREAD

**Issue by marlonnardi** [Spelt/ZXing.Delphi#91]
[DCC Error] E2597 C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-ndk-r17b\toolchains\aarch64-linux-android-4.9\prebuilt\windows\aarch64-linux-android\bin\ld.exe: skipping incompatible simd\libfastutils-android-thumb.a when searching for -lfastutils-android-thumb
  C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-ndk-r17b\toolchains\aarch64-linux-android-4.9\prebuilt\windows\aarch64-linux-android\bin\ld.exe: cannot find -lfastutils-android-thumb

**Comment by Spelt** [comment]
Hi

Using Rio 10.3.3 ?

Op za 23 nov. 2019 om 18:46 schreef Marlon Nardi <notifications@github.com>:

**Comment by marlonnardi** [comment]
Hi Spelt, Yes
Delphi 10.3.3 Version 26.0.36039.7899

**Comment by Spelt** [comment]
Did not test that one. Sounds like the lib linked in is not (yet) compatible with 64bit.

**Comment by marlonnardi** [comment]
I'll try to talk to Erik van Bilsen

**Comment by erikvanbilsen** [comment]
I added 64-bit Android version to original RSP:
https://quality.embarcadero.com/browse/RSP-10592

**Comment by marlonnardi** [comment]
Very very thanks Erik

**Comment by iwan-c-sugeng** [comment]
Great Erik and Spelt, i just come here to confirm the problem, looks like @marlonnardi already tried it and report it first. 

Thanks a lot to all
