### ISSUE TITLE
Exception class Aborted(6)

### ISSUE THREAD

**Issue by ArnaudMN** [Spelt/ZXing.Delphi#97]
I have a problem with sample FmxAdvancedTestApp, with a Galaxy Tab S2 (android). 
In Delphi debugger, when I scan ON, I have message : "Project xxx.apk raised exception class Aborted (6).".

If I replace BUFFER_COUNT = 10 => BUFFER_COUNT = 3, it works properly.

Is this a known problem?

**Comment by Spelt** [comment]
Never heard about it.  

Its not a problem the change the buffer count. A buffer of 3 should be good too.

**Comment by ArnaudMN** [comment]
ok thank you

**Comment by SergioMissias** [comment]
Where do I change the BUFFER_COUNT? THANKS

**Comment by Spelt** [comment]
Thats part of the Advanced Camera Demo which is dropped from the project a few years back due to 'Out of scope' and difficult to maintain. There are alternatives too.  You have to go back to v3.9.1. (2020/03/07) of you want to check out the advanced demo.
