### ISSUE TITLE
Getting Assertion Failure for FastUtils.ps

### ISSUE THREAD

**Issue by RaySa74** [Spelt/ZXing.Delphi#98]
when ruining FmxAdvancedTestApp on oneplus gm1900. i will get Assertion Failure when trying to switch on the camera. 
Please Help

see attached image
thanks
![Screenshot_20200428-153920](https://user-images.githubusercontent.com/52834910/80488986-de27ab80-8967-11ea-8032-52553b1c6600.jpg)

**Comment by RaySa74** [comment]
Assertion Failure in procedure  RotateBitmap  ((Assert((ASrcHeight and 3) = 0); ))

procedure RotateBitmap(const ASrc, ADst: Pointer; const ASrcWidth,
  ASrcHeight: Integer; const AAngle: Integer);
begin
  if (ASrcWidth <= 0) or (ASrcHeight <= 0) then
    Exit;

  Assert(Assigned(ASrc));
  Assert(Assigned(ADst));
   **Assert((ASrcHeight and 3) = 0,'ASrcHeight='+inttostr(ASrcHeight)+'--'+'ASrcWidth='+inttostr(ASrcWidth));  ---------------->Assertion  ERROR** 
  Assert((ASrcWidth and 3) = 0);

  case AAngle of
      0: RotateBitmap0Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
     90: RotateBitmap90Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
    180: RotateBitmap180Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
    270: RotateBitmap270Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
  else
    Assert(False);
  end;
end;

![Screenshot_20200428-191423eeeeeeeeeeeee](https://user-images.githubusercontent.com/52834910/80512098-ab8cab80-8985-11ea-94c5-4e636a7e1556.jpg)

**Comment by Spelt** [comment]
This is because you need to include the android files in your project path.

**Comment by RaySa74** [comment]
I tried to debug it and the value of ASrcHeight  comes out to be 738 and this will cause the error. Please see the image from the previous reply.  (738and3=2 not 0)

**Comment by Spelt** [comment]
Yes but that comes because some dependency is not included right. Watch out for 64/32 bit differences. 

Also read the text on the git page below:

NOTE for 'Advanced test demo app' and Android with Rio.


Take care.

**Comment by RaySa74** [comment]
when i fix the Search Path to \simd;\custom the problem Assertion Failure is fixed but the the camera becomes very slow and lagging frame rate 10??
when i set the Search path to simd;custom and disable Assert((ASrcWidth and 3) = 0); and Assert((ASrcHeight and 3) = 0); the camera work very well and frame rate is 30

Please what to do??  
thanks for your patience 

![fix](https://user-images.githubusercontent.com/52834910/80534050-4d70c000-89a7-11ea-9f1a-1d325d261f47.png)

procedure RotateBitmap(const ASrc, ADst: Pointer; const ASrcWidth,
  ASrcHeight: Integer; const AAngle: Integer);
 var
 dfd:integer;
  begin
  if (ASrcWidth <= 0) or (ASrcHeight <= 0) then
    Exit;

  Assert(Assigned(ASrc));
  Assert(Assigned(ADst));


//  Assert((ASrcHeight and 3) = 0,'ASrcHeight='+inttostr(ASrcHeight)+'--'+'ASrcWidth='+inttostr(ASrcWidth));
//  Assert((ASrcWidth and 3) = 0);



  case AAngle of
      0: RotateBitmap0Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
     90: RotateBitmap90Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
    180: RotateBitmap180Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
    270: RotateBitmap270Degrees(ASrc, ADst, ASrcWidth, ASrcHeight);
  else
    Assert(False);
  end;
end;

**Comment by Spelt** [comment]
I added this library to enhance the camera because the standard camera is kinda slow. 

Its actually not part of the zxing library and I cannot support it because it has its own manual

I suggest that you dont continue with this lib and stop wasting your time and buy native camera component from winsoft.sk or somewhere else. 

Im thinking of removing this lib from this repo because its sometimes to advanced for a lot of users. 

I hope you agree. 

Edward
